import { Link, Navigate, useParams } from "react-router-dom";
import Layout from "../../components/layout/Layout";
import SEO from "../../components/seo/SEO";
import RelatedTools from "../../components/seo/RelatedTools";

const guides = [
  { slug: "how-to-convert-jpg-to-pdf", title: "How to convert JPG photos to one PDF", description: "A practical way to arrange photographed pages, receipts, or images into one PDF.", tool: "/jpg-to-pdf", toolName: "JPG to PDF", intro: "A PDF is easier to upload or share than a run of separate photos. Start with clear JPG or JPEG files, then make the page order match the order someone should read them.", steps: ["Choose JPG or JPEG photos that are upright and readable.", "Open JPG to PDF, add up to 20 files, and use the previews to check the sequence.", "Drag previews into reading order, create the PDF, and download it."], tips: ["Use even lighting for document photos.", "Retake blurry pages before conversion.", "Use Document Scanner when you need trimming, scan modes, or page numbers."] },
  { slug: "how-to-convert-png-to-pdf", title: "How to turn PNG screenshots into a PDF", description: "Prepare screenshots, diagrams, and interface images for one readable PDF document.", tool: "/png-to-pdf", toolName: "PNG to PDF", intro: "PNG works well for screenshots and diagrams. Combining them into a PDF is useful for a support ticket, design review, or a step-by-step record.", steps: ["Collect the final screenshots and make sure sensitive information is removed.", "Upload up to 20 PNGs to PNG to PDF and order them as the workflow happened.", "Create the PDF and review the downloaded file before sending it."], tips: ["PNG transparency is placed over white in the PDF.", "Keep screenshots at a legible size.", "Resize a batch first if the images need consistent dimensions."] },
  { slug: "how-to-scan-document-photos-to-pdf", title: "How to scan document photos into a PDF", description: "Create a cleaner multi-page PDF from phone photos with the available scanner controls.", tool: "/document-scanner", toolName: "Document Scanner", intro: "Document Scanner helps turn up to 20 photographed pages into an A4 PDF. It is intended for papers such as forms, notes, and certificates—not as a replacement for reviewing the original document.", steps: ["Photograph each page flat, in good light, with all text visible.", "Upload JPG, PNG, or WEBP photos and review the preview and any blank or blurry warnings.", "Choose white-edge trimming, a color mode, rotation, page numbers, and a size goal, then create the PDF."], tips: ["Use grayscale or black-and-white for text-heavy pages when appropriate.", "A size goal adjusts image quality; final size depends on the pages.", "Preview every photo before creating the PDF."] },
  { slug: "how-to-package-multiple-pdfs-into-a-zip", title: "How to package multiple PDFs in a ZIP file", description: "Send several unchanged PDFs as one downloadable archive.", tool: "/pdf-to-zip", toolName: "PDF to ZIP", intro: "A ZIP archive keeps several PDFs together while leaving their PDF pages and contents unchanged. It is useful for related forms, invoices, or project documents.", steps: ["Gather up to 20 PDFs, each no larger than 25 MB.", "Add them to PDF to ZIP, remove anything that should not be included, and choose an archive filename.", "Create and download the ZIP, then open it locally to verify the contents."], tips: ["ZIP packaging does not promise a smaller total size.", "Use descriptive PDF filenames before packaging.", "Create photo PDFs first with an image-to-PDF tool if needed."] },
  { slug: "how-to-resize-multiple-images", title: "How to resize multiple images without stretching", description: "Use pixels or percentage settings to prepare a batch of image files for upload or sharing.", tool: "/resize-image", toolName: "Resize Image", intro: "Resizing changes image dimensions; it is not the same as cropping. QuickPDFHD can resize up to 20 JPG, PNG, or WEBP images and returns the batch in a ZIP archive.", steps: ["Add up to 20 images, each under 10 MB and no more than 8000 px in either dimension.", "Use Pixels with aspect-ratio lock on so width and height stay proportional, or Percentage to scale each file by the same amount.", "Unlock aspect ratio only when you want exact width and height and are willing to stretch the image, then download the ZIP."], tips: ["Keep the lock on to avoid crop, stretch, and extra white bars.", "JPG and WEBP have a quality control; PNG does not.", "Use dimensions required by your destination rather than an arbitrary preset."] },
];

const guideUrl = (slug) => `https://quickpdfhd.com/pdf-guides/${slug}`;

export const PdfGuides = () => <Layout><SEO title="PDF Guides | QuickPDFHD" description="Practical guides for QuickPDFHD's JPG, PNG, document scanning, PDF ZIP, and image resizing tools." canonical="https://quickpdfhd.com/pdf-guides" /><main>
  <section className="bg-slate-50 py-16 text-center sm:py-20"><div className="mx-auto max-w-3xl px-4 sm:px-6"><p className="text-sm font-semibold uppercase tracking-wide text-teal-800">QuickPDFHD help</p><h1 className="mt-3 text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">PDF guides for real file tasks</h1><p className="mt-5 text-lg leading-8 text-slate-600">Short, practical instructions for the tools already available on QuickPDFHD.</p></div></section>
  <section className="bg-white py-16 sm:py-20"><div className="mx-auto grid max-w-5xl gap-6 px-4 sm:grid-cols-2 sm:px-6">{guides.map((guide) => <article key={guide.slug} className="rounded-2xl border border-slate-200 p-7 shadow-sm"><h2 className="text-2xl font-bold text-slate-900"><Link to={`/pdf-guides/${guide.slug}`} className="hover:text-teal-800">{guide.title}</Link></h2><p className="mt-4 leading-7 text-slate-600">{guide.description}</p><Link to={`/pdf-guides/${guide.slug}`} className="mt-5 inline-block font-semibold text-teal-800 hover:underline">Read guide →</Link></article>)}</div></section>
</main></Layout>;

export const PdfGuide = () => {
  const { slug } = useParams();
  const guide = guides.find((entry) => entry.slug === slug);
  if (!guide) return <Navigate to="/page-not-found" replace />;
  const canonical = guideUrl(guide.slug);
  return <Layout><SEO title={`${guide.title} | QuickPDFHD`} description={guide.description} canonical={canonical} structuredData={{ "@context": "https://schema.org", "@type": "Article", headline: guide.title, description: guide.description, mainEntityOfPage: canonical }} /><main>
    <section className="bg-slate-50 py-16 sm:py-20"><div className="mx-auto max-w-3xl px-4 sm:px-6"><nav aria-label="Breadcrumb" className="text-sm text-slate-500"><Link to="/">Home</Link> <span aria-hidden="true">/</span> <Link to="/pdf-guides">PDF Guides</Link> <span aria-hidden="true">/</span> {guide.title}</nav><h1 className="mt-5 text-4xl font-extrabold tracking-tight text-slate-900 sm:text-5xl">{guide.title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{guide.intro}</p></div></section>
    <article className="bg-white py-16 sm:py-20"><div className="mx-auto max-w-3xl px-4 sm:px-6"><h2 className="text-3xl font-bold text-slate-900">Steps</h2><ol className="mt-7 space-y-5">{guide.steps.map((step, index) => <li key={step} className="rounded-2xl border border-slate-200 p-6 leading-7 text-slate-600"><span className="mr-3 font-bold text-teal-800">{index + 1}.</span>{step}</li>)}</ol><h2 className="mt-12 text-3xl font-bold text-slate-900">Useful checks</h2><ul className="mt-6 list-disc space-y-3 pl-6 leading-7 text-slate-600">{guide.tips.map((tip) => <li key={tip}>{tip}</li>)}</ul><div className="mt-12 rounded-2xl bg-teal-50 p-7"><h2 className="text-2xl font-bold text-slate-900">Ready to try it?</h2><p className="mt-3 leading-7 text-slate-600">Open the {guide.toolName} workspace to complete this task.</p><Link to={`${guide.tool}#upload`} className="mt-5 inline-block rounded-xl bg-teal-600 px-5 py-3 font-semibold text-white hover:bg-teal-700">Open {guide.toolName}</Link></div></div></article>
    <RelatedTools currentPath={guide.tool} />
  </main></Layout>;
};
