const site = "https://quickpdfhd.com";

const privacyNote =
  "Files are uploaded to QuickPDFHD's conversion server and processed in memory to create your download. The application does not write uploaded files to its own disk or database. Use the tool only for files you are allowed to process.";

export const documentTools = {
  "word-to-pdf": {
    id: "word-to-pdf",
    name: "Word to PDF",
    path: "/word-to-pdf",
    canonical: `${site}/word-to-pdf`,
    title: "Word to PDF Converter Online – DOC & DOCX | QuickPDFHD",
    description:
      "Convert Word documents to PDF online. Upload a DOC or DOCX file, create a printable PDF, and download it from your browser. No account required.",
    heading: "Convert Word Documents to PDF Online",
    intro:
      "Turn a Word document into a PDF when you need a file that is easier to print, attach, or send without relying on Microsoft Word on the other end. Upload a .doc or .docx file and download a PDF built from the document's readable text, headings, lists, tables, and embedded images.",
    badge: "Word to PDF converter",
    endpoint: "/api/pdf-tools/word-to-pdf",
    accept: ".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    extensions: [".doc", ".docx"],
    mimeTypes: [
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/octet-stream",
    ],
    multiple: false,
    maxFiles: 1,
    maxSize: 15 * 1024 * 1024,
    maxSizeLabel: "15 MB",
    formatsLabel: "DOC and DOCX (.doc, .docx)",
    uploadTitle: "Upload a Word document",
    uploadHint: "Drop a .doc or .docx file here or choose one from your device · 15 MB maximum",
    actionLabel: "Convert Word to PDF",
    processingLabel: "Converting Word document...",
    successTitle: "Your PDF is ready",
    downloadLabel: "Download PDF",
    downloadName: "QuickPDFHD-word.pdf",
    howTitle: "How to convert a Word document to PDF",
    howIntro: "The converter reads the uploaded Word file on the server and builds a PDF from its content. It is meant for letters, notes, reports, and other text-based documents.",
    steps: [
      { title: "Choose a Word file", description: "Upload one .doc or .docx document up to 15 MB." },
      { title: "Start conversion", description: "Select Convert Word to PDF. Processing happens on the server, not in your browser bundle." },
      { title: "Review the PDF", description: "Download the generated PDF and check that the text and structure match what you need." },
    ],
    features: [
      { title: "DOC and DOCX support", description: "Modern Word files (.docx) are converted from their document structure. Older .doc files are converted from extracted text." },
      { title: "Shareable output", description: "A PDF is useful when the recipient should open the file without editing it in Word." },
      { title: "Layout-conscious conversion", description: "Headings, paragraphs, lists, tables, and common embedded images are carried into the PDF. Complex Word themes are simplified." },
    ],
    explanationTitle: "What this Word to PDF tool does",
    explanation: [
      "People convert Word documents to PDF when a file needs to travel as a document rather than an editable draft. Job applications, letters, classroom handouts, and internal reports are typical examples.",
      "QuickPDFHD reads the uploaded DOC or DOCX file and writes a PDF that contains the document's text and basic structure. That is a real conversion of the file contents, not a renamed extension.",
      "Pixel-perfect reproduction of every Word style, header graphic, or tracked-change view is not the goal. If a document relies on unusual fonts, text boxes, or macros, check the PDF after conversion.",
    ],
    usesTitle: "When Word to PDF is useful",
    uses: [
      "Sending a letter or resume as a PDF attachment",
      "Preparing a printable version of a report written in Word",
      "Sharing a document with someone who does not use Microsoft Word",
      "Creating a more stable file for printing or uploading to a portal",
    ],
    tipsTitle: "Tips for a cleaner Word to PDF conversion",
    tips: [
      "Use a finished document rather than a file full of comments and tracked changes if you only need the visible text.",
      "DOCX usually preserves more structure than a very old .doc file.",
      "If the PDF shows question marks in place of special characters, those characters were outside the PDF text encoding used for this converter.",
    ],
    privacy: privacyNote,
    related: ["/pdf-to-word", "/excel-to-pdf", "/pdf-to-excel"],
    faqs: [
      { question: "How do I convert Word to PDF?", answer: "Upload a .doc or .docx file, choose Convert Word to PDF, then download the generated PDF." },
      { question: "Can I convert DOCX to PDF?", answer: "Yes. DOCX files are the primary Word format this converter is built for." },
      { question: "Can I convert DOC files as well?", answer: "Yes. Legacy .doc files are accepted. The PDF is built from the extracted document text." },
      { question: "Will formatting be preserved?", answer: "Headings, paragraphs, lists, tables, and common images are included. Advanced Word layout, custom fonts, and design themes may look simpler in the PDF." },
      { question: "Can I convert Word documents online?", answer: "Yes. The tool runs in your browser and sends the file to QuickPDFHD's server only to create the PDF." },
      { question: "Is there a file size limit?", answer: "Each Word file can be up to 15 MB." },
      { question: "Do I need Microsoft Word installed?", answer: "No. Conversion happens through the web tool." },
      { question: "Are files stored after conversion?", answer: "Uploaded files are processed in memory to create your PDF. The application does not write them to its own disk or database." },
    ],
  },
  "pdf-to-word": {
    id: "pdf-to-word",
    name: "PDF to Word",
    path: "/pdf-to-word",
    canonical: `${site}/pdf-to-word`,
    title: "PDF to Word Converter Online – PDF to DOCX | QuickPDFHD",
    description:
      "Convert a PDF to an editable Word DOCX file online. Extract selectable text from a PDF and download a Word document you can open and edit.",
    heading: "Convert PDF to an Editable Word Document",
    intro:
      "Use PDF to Word when you need the text from a PDF in a DOCX file you can edit. The converter extracts selectable text from each page and writes a Word document. It is not an OCR product, so scanned or image-only PDFs cannot be turned into editable text.",
    badge: "PDF to Word converter",
    endpoint: "/api/pdf-tools/pdf-to-word",
    accept: ".pdf,application/pdf",
    extensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    multiple: false,
    maxFiles: 1,
    maxSize: 25 * 1024 * 1024,
    maxSizeLabel: "25 MB",
    formatsLabel: "PDF (.pdf) with selectable text",
    uploadTitle: "Upload a PDF",
    uploadHint: "Drop a PDF here or choose a file · up to 40 pages · 25 MB maximum",
    actionLabel: "Convert PDF to Word",
    processingLabel: "Extracting text into Word...",
    successTitle: "Your Word file is ready",
    downloadLabel: "Download DOCX",
    downloadName: "QuickPDFHD-document.docx",
    howTitle: "How to convert a PDF to Word",
    howIntro: "The server reads text objects from the PDF and places them into a DOCX file, page by page.",
    steps: [
      { title: "Upload the PDF", description: "Choose a PDF that contains selectable text, up to 25 MB and 40 pages." },
      { title: "Convert to DOCX", description: "Select Convert PDF to Word to extract the text into a Word document." },
      { title: "Edit the result", description: "Download the DOCX and continue editing in Word or another compatible editor." },
    ],
    features: [
      { title: "DOCX output", description: "The download is a standard .docx file, not a renamed PDF." },
      { title: "Page-aware extraction", description: "Text is grouped by page so you can see where each block came from." },
      { title: "Honest limits", description: "Image-only scans need OCR, which this tool does not perform." },
    ],
    explanationTitle: "What PDF to Word can and cannot do",
    explanation: [
      "A PDF is often a finished layout. Converting it to Word is useful when you need to reuse paragraphs, fix a sentence, or move content into another document.",
      "This converter extracts selectable text. Tables and columns in the PDF may appear as sequential lines rather than a perfect Word table. Decorative layout is not rebuilt.",
      "If you cannot highlight text in a PDF viewer, the file is likely a scan. Convert that kind of file only after text has been made selectable elsewhere, or use it as a visual PDF instead.",
    ],
    usesTitle: "Common PDF to Word uses",
    uses: [
      "Recovering wording from a text-based PDF so you can edit it",
      "Moving report content into a Word draft",
      "Copying headings and body text without retyping",
      "Preparing an editable file when the original Word document is missing",
    ],
    tipsTitle: "Formatting expectations",
    tips: [
      "Check tables after conversion. Complex grids often need cleanup in Word.",
      "Keep native PDFs exported from Word, Excel, or a text editor; they convert more reliably than photographed pages.",
      "Password-protected PDFs need to be unlocked before upload.",
    ],
    privacy: privacyNote,
    related: ["/word-to-pdf", "/pdf-to-excel", "/split-pdf"],
    faqs: [
      { question: "Can I edit a PDF in Word after conversion?", answer: "Yes, if the PDF contained selectable text. The DOCX can be opened and edited in Word. Layout may differ from the original PDF." },
      { question: "Can I convert PDF to DOCX?", answer: "Yes. The output is a .docx Word document." },
      { question: "What happens to tables?", answer: "Table text is extracted. Column alignment from the PDF is approximated from reading order and may need adjustment in Word." },
      { question: "Can scanned PDFs be converted?", answer: "Not into editable text. Scanned or image-only PDFs have no selectable text for this tool to extract." },
      { question: "Why can formatting change?", answer: "A PDF stores positioned text, not a Word document structure. The converter rebuilds paragraphs from that text." },
      { question: "Is there a page limit?", answer: "PDFs of up to 40 pages and 25 MB are accepted." },
      { question: "Do I need an account?", answer: "No. Conversion works in the browser without signing in." },
    ],
  },
  "excel-to-pdf": {
    id: "excel-to-pdf",
    name: "Excel to PDF",
    path: "/excel-to-pdf",
    canonical: `${site}/excel-to-pdf`,
    title: "Excel to PDF Converter Online – XLS & XLSX | QuickPDFHD",
    description:
      "Convert Excel spreadsheets to PDF online. Upload an XLS or XLSX file and download a printable PDF of your worksheet tables.",
    heading: "Convert Excel Spreadsheets to PDF Online",
    intro:
      "Create a PDF from an Excel workbook when you want to share a table as a document instead of a spreadsheet. Upload an .xls or .xlsx file and download a landscape PDF that lays out worksheet rows and columns for reading or printing.",
    badge: "Excel to PDF converter",
    endpoint: "/api/pdf-tools/excel-to-pdf",
    accept: ".xls,.xlsx,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    extensions: [".xls", ".xlsx"],
    mimeTypes: [
      "application/vnd.ms-excel",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "application/octet-stream",
    ],
    multiple: false,
    maxFiles: 1,
    maxSize: 15 * 1024 * 1024,
    maxSizeLabel: "15 MB",
    formatsLabel: "XLS and XLSX (.xls, .xlsx)",
    uploadTitle: "Upload an Excel file",
    uploadHint: "Drop an .xls or .xlsx workbook here or choose a file · 15 MB maximum",
    actionLabel: "Convert Excel to PDF",
    processingLabel: "Building PDF from spreadsheet...",
    successTitle: "Your spreadsheet PDF is ready",
    downloadLabel: "Download PDF",
    downloadName: "QuickPDFHD-excel.pdf",
    howTitle: "How to convert Excel to PDF",
    howIntro: "The converter reads worksheet cells and draws them as a table on PDF pages. Charts, macros, and pivot caches are not rendered as Excel objects.",
    steps: [
      { title: "Select a workbook", description: "Upload one XLS or XLSX file up to 15 MB." },
      { title: "Convert the sheets", description: "Each worksheet with data is added to the PDF as a table." },
      { title: "Download the PDF", description: "Open the PDF to review wrapping, column limits, and page breaks." },
    ],
    features: [
      { title: "Spreadsheet to document", description: "Useful when a recipient should view the numbers without opening Excel." },
      { title: "Multi-sheet workbooks", description: "Worksheets with data are included, each labeled with the sheet name." },
      { title: "Print-oriented pages", description: "The PDF uses landscape pages so more columns fit on a row." },
    ],
    explanationTitle: "How spreadsheet conversion works here",
    explanation: [
      "Excel files store cells, formulas, and formatting. This tool converts the displayed cell values into a table on PDF pages so you can share or print the data.",
      "Very wide sheets are limited to the first 12 columns so the page stays readable. Extremely long sheets include up to 400 populated rows per worksheet.",
      "Formulas are not recalculated. The PDF shows the values stored in the file. Hidden sheets with no readable rows are skipped.",
    ],
    usesTitle: "Typical Excel to PDF use cases",
    uses: [
      "Sending a budget table as a PDF attachment",
      "Printing a class list, inventory, or attendance sheet",
      "Sharing a report table with people who should not edit the workbook",
      "Archiving a snapshot of worksheet data",
    ],
    tipsTitle: "Best practices",
    tips: [
      "Put the important columns on the left if the sheet is wider than 12 columns.",
      "Remove unused blank rows so the PDF stays short.",
      "If you need charts as images, export those from Excel first and use an image-to-PDF tool.",
    ],
    privacy: privacyNote,
    related: ["/pdf-to-excel", "/word-to-pdf", "/pdf-to-word"],
    faqs: [
      { question: "How do I convert Excel to PDF?", answer: "Upload an XLS or XLSX file and choose Convert Excel to PDF. Download the generated PDF when it is ready." },
      { question: "Can I convert XLSX to PDF?", answer: "Yes. XLSX is fully supported. Older XLS workbooks are also accepted." },
      { question: "Are formulas converted?", answer: "The PDF shows stored cell values. Formulas are not recalculated during conversion." },
      { question: "Do charts appear in the PDF?", answer: "No. This converter focuses on worksheet tables, not Excel charts or macros." },
      { question: "What if my sheet has many columns?", answer: "Up to 12 columns are drawn so the landscape page remains readable. Move key columns left before converting if needed." },
      { question: "Is there a file size limit?", answer: "Each spreadsheet can be up to 15 MB." },
      { question: "Can I convert several sheets at once?", answer: "Yes. Worksheets that contain data are included in one PDF." },
    ],
  },
  "pdf-to-excel": {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    path: "/pdf-to-excel",
    canonical: `${site}/pdf-to-excel`,
    title: "PDF to Excel Converter Online – Extract Tables to XLSX | QuickPDFHD",
    description:
      "Convert PDF tables to Excel online. Extract selectable text from a PDF into an XLSX spreadsheet you can sort, filter, and edit.",
    heading: "Extract PDF Tables into an Excel Spreadsheet",
    intro:
      "PDF to Excel is for pulling readable table-like text out of a PDF and into an .xlsx file. Each PDF page becomes a worksheet. The result is useful when you need to sort or calculate values that currently live in a text-based PDF.",
    badge: "PDF to Excel converter",
    endpoint: "/api/pdf-tools/pdf-to-excel",
    accept: ".pdf,application/pdf",
    extensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    multiple: false,
    maxFiles: 1,
    maxSize: 25 * 1024 * 1024,
    maxSizeLabel: "25 MB",
    formatsLabel: "PDF (.pdf) with selectable table text",
    uploadTitle: "Upload a PDF with tables",
    uploadHint: "Drop a PDF here or choose a file · up to 40 pages · 25 MB maximum",
    actionLabel: "Convert PDF to Excel",
    processingLabel: "Extracting tables into Excel...",
    successTitle: "Your Excel file is ready",
    downloadLabel: "Download XLSX",
    downloadName: "QuickPDFHD-tables.xlsx",
    howTitle: "How to convert a PDF to Excel",
    howIntro: "The converter groups text by its position on each page, then writes those groups into spreadsheet rows.",
    steps: [
      { title: "Upload the PDF", description: "Use a PDF where you can select table text with a mouse, not a photograph of a page." },
      { title: "Extract the data", description: "Select Convert PDF to Excel to build an XLSX workbook from the detected rows." },
      { title: "Clean up in Excel", description: "Open the file, check columns, and split any cells that still contain combined text." },
    ],
    features: [
      { title: "XLSX download", description: "You receive a real spreadsheet, not a PDF with a spreadsheet extension." },
      { title: "One sheet per page", description: "Each PDF page is written to its own worksheet for easier checking." },
      { title: "Built for table-like PDFs", description: "Reports, invoices, and exported lists convert more reliably than free-form posters." },
    ],
    explanationTitle: "Table extraction, not magic OCR",
    explanation: [
      "Business PDFs often hide useful numbers inside a layout that is hard to copy. This tool reconstructs rows from the position of selectable text.",
      "Merged cells, nested headers, and multi-line cells can land in the wrong column. Always review the spreadsheet before using it in a report.",
      "Scanned PDFs and image-only invoices have no text to extract. Those files will be rejected rather than filled with blank sheets.",
    ],
    usesTitle: "Where PDF to Excel helps",
    uses: [
      "Moving a statement table into a workbook you can filter",
      "Reusing figures from a PDF report without retyping",
      "Comparing exported lists once they are in Excel",
      "Preparing data for a chart after a cleanup pass",
    ],
    tipsTitle: "Get better columns",
    tips: [
      "Start with PDFs exported from Excel, accounting software, or a reporting tool.",
      "If two columns collapse into one cell, split them in Excel after download.",
      "Unlock password-protected PDFs before uploading.",
    ],
    privacy: privacyNote,
    related: ["/excel-to-pdf", "/pdf-to-word", "/merge-pdf"],
    faqs: [
      { question: "How do I convert PDF to Excel?", answer: "Upload a text-based PDF and choose Convert PDF to Excel. Download the XLSX file and review the columns." },
      { question: "Can I extract a table from a PDF?", answer: "Yes, when the table is made of selectable text. The extractor groups that text into rows." },
      { question: "What file do I get?", answer: "An .xlsx workbook. Each PDF page is a worksheet." },
      { question: "Can scanned PDFs be converted?", answer: "No. Image-only scans need OCR first. This tool only extracts existing text." },
      { question: "Will every column be perfect?", answer: "Not always. Complex or tightly designed tables often need a cleanup pass in Excel." },
      { question: "Is there a size limit?", answer: "The PDF can be up to 25 MB and 40 pages." },
      { question: "Can I convert PDF to XLSX without Excel installed?", answer: "Yes. The conversion runs online. You only need Excel or another spreadsheet app if you want to edit the result." },
    ],
  },
  "split-pdf": {
    id: "split-pdf",
    name: "Split PDF",
    path: "/split-pdf",
    canonical: `${site}/split-pdf`,
    title: "Split PDF Online – Extract Pages from a PDF | QuickPDFHD",
    description:
      "Split a PDF online. Extract a page range, save each page as its own PDF, or divide a large document into smaller files. Original pages stay intact.",
    heading: "Split a PDF or Extract Selected Pages",
    intro:
      "Split PDF is for taking pages out of a larger document. Extract a range into one smaller PDF, save each page as a separate file, or break a long file into chunks. The original page content is copied, not re-rendered.",
    badge: "Split PDF tool",
    endpoint: "/api/pdf-tools/split",
    accept: ".pdf,application/pdf",
    extensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    multiple: false,
    maxFiles: 1,
    maxSize: 25 * 1024 * 1024,
    maxSizeLabel: "25 MB",
    formatsLabel: "PDF (.pdf)",
    uploadTitle: "Upload a PDF to split",
    uploadHint: "Drop a PDF here or choose a file · up to 200 pages · 25 MB maximum",
    actionLabel: "Split PDF",
    processingLabel: "Splitting PDF...",
    successTitle: "Your split PDF is ready",
    downloadLabel: "Download file",
    downloadName: "QuickPDFHD-extracted-pages.pdf",
    extra: "split",
    howTitle: "How to split a PDF",
    howIntro: "Choose the outcome you need, then run the split. Page numbers start at 1.",
    steps: [
      { title: "Upload one PDF", description: "Add a PDF up to 25 MB. Password-protected files need to be unlocked first." },
      { title: "Choose a split mode", description: "Extract a range, export every selected page as its own PDF, or split into equal chunks." },
      { title: "Download the result", description: "A single PDF is returned for range extraction. Other modes return a ZIP of PDF files." },
    ],
    features: [
      { title: "Extract a page range", description: "Use values such as 1-3, 5, 8-10 to keep only those pages in one PDF." },
      { title: "Separate pages", description: "Create one PDF file per page when you need to send or archive pages individually." },
      { title: "Chunk a long file", description: "Split a large PDF into smaller documents with a fixed number of pages each." },
    ],
    explanationTitle: "What splitting a PDF actually does",
    explanation: [
      "Splitting copies pages from the source PDF into a new file. The pages themselves are not flattened into images, so vector text and existing page size are preserved.",
      "The original upload is not modified on your device. You still have the full document unless you replace it yourself.",
      "Use extract-range when a reviewer only needs a chapter. Use separate pages when each form or certificate should be its own file.",
    ],
    usesTitle: "Practical split PDF uses",
    uses: [
      "Sending only the pages a client asked for",
      "Separating scanned certificates that arrived as one file",
      "Breaking a large handbook into email-sized chunks",
      "Pulling an appendix out of a longer report",
    ],
    tipsTitle: "Page ranges",
    tips: [
      "Numbering follows the PDF file order, which may differ from printed page numbers.",
      "Leave the range blank in separate-pages or extract mode to use every page.",
      "Encrypted PDFs cannot be split until the password is removed.",
    ],
    privacy: privacyNote,
    related: ["/merge-pdf", "/pdf-to-jpg", "/pdf-to-word"],
    faqs: [
      { question: "How do I split a PDF into separate pages?", answer: "Upload the PDF, choose Separate pages, and download the ZIP. Each selected page becomes its own PDF." },
      { question: "Can I extract specific pages?", answer: "Yes. Choose Extract range and enter pages such as 1-4, 9." },
      { question: "Can I split a large PDF?", answer: "Yes, within the 25 MB and 200-page limits. Chunk mode creates several smaller PDFs." },
      { question: "Is the original PDF modified?", answer: "No. A new file is generated. Your original file stays on your device unless you overwrite it." },
      { question: "Do pages stay in order?", answer: "Yes. Extracted pages keep the order you requested." },
      { question: "What download do I get?", answer: "Extract range returns one PDF. Separate pages and chunks return a ZIP archive of PDFs." },
      { question: "Can I use this on a phone?", answer: "Yes. Choose the PDF from your device and download the result when processing finishes." },
    ],
  },
  "merge-pdf": {
    id: "merge-pdf",
    name: "Merge PDF",
    path: "/merge-pdf",
    canonical: `${site}/merge-pdf`,
    title: "Merge PDF Files Online – Combine Multiple PDFs | QuickPDFHD",
    description:
      "Merge PDF files online. Combine multiple PDFs in the order you choose and download one document. Page content is copied, not converted to images.",
    heading: "Merge Multiple PDF Files into One Document",
    intro:
      "Combine PDFs when related documents should travel as a single file. Upload two or more PDFs, set the file order, and download one document that contains every page in that sequence.",
    badge: "Merge PDF tool",
    endpoint: "/api/pdf-tools/merge",
    accept: ".pdf,application/pdf",
    extensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    multiple: true,
    maxFiles: 20,
    maxSize: 25 * 1024 * 1024,
    maxSizeLabel: "25 MB each",
    formatsLabel: "PDF (.pdf), up to 20 files",
    uploadTitle: "Upload PDF files to merge",
    uploadHint: "Drop PDFs here or choose files · 2 to 20 files · 25 MB each",
    actionLabel: "Merge PDFs",
    processingLabel: "Merging PDFs...",
    successTitle: "Your merged PDF is ready",
    downloadLabel: "Download merged PDF",
    downloadName: "QuickPDFHD-merged.pdf",
    extra: "merge",
    howTitle: "How to merge PDF files",
    howIntro: "The merge copies pages from each file in list order. Rearrange files before you run it.",
    steps: [
      { title: "Add the PDFs", description: "Upload at least two PDF files, up to 20 in total." },
      { title: "Set the order", description: "Move files up or down so chapters, invoices, or forms appear in the right sequence." },
      { title: "Create one PDF", description: "Select Merge PDFs and download the combined document." },
    ],
    features: [
      { title: "Preserve page order", description: "Files are joined in the list order you set. Pages inside each file keep their original order." },
      { title: "Keep existing pages", description: "Pages are copied from the source PDFs rather than photographed." },
      { title: "Organize related documents", description: "Useful for packets, applications, and multi-part reports." },
    ],
    explanationTitle: "Combining PDFs without flattening them",
    explanation: [
      "Merging is a document-organization task. Instead of attaching five files, you attach one PDF that already contains them in reading order.",
      "Each source page is copied into the new file. Mixed page sizes stay as they were in the originals.",
      "The tool does not redesign layouts or add a table of contents. If you only need a subset of pages, split first, then merge.",
    ],
    usesTitle: "Common merge PDF workflows",
    uses: [
      "Joining a cover letter and a portfolio into one application PDF",
      "Combining weekly reports into a monthly packet",
      "Putting signed forms and ID scans into one submission file",
      "Assembling class materials that arrived as separate downloads",
    ],
    tipsTitle: "Before you merge",
    tips: [
      "Rename files so the list is easy to check.",
      "Unlock password-protected PDFs first.",
      "If a file is a scan of many receipts, split out the pages you actually need, then merge.",
    ],
    privacy: privacyNote,
    related: ["/split-pdf", "/word-to-pdf", "/pdf-to-jpg"],
    faqs: [
      { question: "How do I merge PDF files?", answer: "Upload two or more PDFs, arrange them in order, and choose Merge PDFs. Download the combined document." },
      { question: "Can I combine more than two PDFs?", answer: "Yes. You can merge up to 20 PDF files in one operation." },
      { question: "Can I change the file order?", answer: "Yes. Use the move controls on each file before merging." },
      { question: "Are pages converted to images?", answer: "No. Existing PDF pages are copied into the new file." },
      { question: "Is there a size limit?", answer: "Each PDF can be up to 25 MB, with a combined limit of 200 pages." },
      { question: "Does merging reduce quality?", answer: "The merge copies pages. It does not recompress them as images." },
      { question: "Can I merge PDFs on mobile?", answer: "Yes. Select files from your phone or tablet and download the result." },
    ],
  },
  "pdf-to-jpg": {
    id: "pdf-to-jpg",
    name: "PDF to JPG",
    path: "/pdf-to-jpg",
    canonical: `${site}/pdf-to-jpg`,
    title: "PDF to JPG Converter Online – Save PDF Pages as Images | QuickPDFHD",
    description:
      "Convert PDF pages to JPG online. Each page is rendered as an image. Download a JPG for a single page or a ZIP of images for multi-page PDFs.",
    heading: "Convert PDF Pages to JPG Images",
    intro:
      "PDF to JPG renders each page of a PDF into a JPEG image. That is useful when a website, chat app, or presentation needs a picture of a page rather than a PDF file. A one-page PDF downloads as a JPG. Longer files download as a ZIP of images.",
    badge: "PDF to JPG converter",
    endpoint: "/api/pdf-tools/pdf-to-jpg",
    accept: ".pdf,application/pdf",
    extensions: [".pdf"],
    mimeTypes: ["application/pdf"],
    multiple: false,
    maxFiles: 1,
    maxSize: 25 * 1024 * 1024,
    maxSizeLabel: "25 MB",
    formatsLabel: "PDF (.pdf)",
    uploadTitle: "Upload a PDF to convert",
    uploadHint: "Drop a PDF here or choose a file · up to 40 pages · 25 MB maximum",
    actionLabel: "Convert PDF to JPG",
    processingLabel: "Rendering PDF pages...",
    successTitle: "Your JPG images are ready",
    downloadLabel: "Download images",
    downloadName: "QuickPDFHD-pdf-pages.zip",
    howTitle: "How to convert a PDF to JPG",
    howIntro: "Each page is drawn as an image on the server, then saved as a JPEG.",
    steps: [
      { title: "Upload the PDF", description: "Choose a PDF up to 40 pages and 25 MB." },
      { title: "Render the pages", description: "Select Convert PDF to JPG. Every page is turned into an image." },
      { title: "Download the images", description: "A single page returns a JPG. Multiple pages return a ZIP of JPG files." },
    ],
    features: [
      { title: "True page rendering", description: "Pages are rasterized, not renamed. You get actual image files of the PDF pages." },
      { title: "One image per page", description: "Page order is kept in the filenames, such as page-001.jpg." },
      { title: "Ready for sharing", description: "JPG is a practical format for previews, slides, and posts that do not accept PDFs." },
    ],
    explanationTitle: "Why convert PDF pages to images",
    explanation: [
      "A PDF is a document. A JPG is a picture of a page. Converting is helpful when the destination cannot display PDFs, or when you only need a snapshot of one page.",
      "Rendering flattens the page: text becomes pixels. You will not be able to copy text from the JPG the way you can from the PDF.",
      "Image quality is set for readable pages at a moderate file size. Extremely small print may need the original PDF for archival use.",
    ],
    usesTitle: "Useful PDF to JPG situations",
    uses: [
      "Creating a preview image of a certificate or flyer",
      "Dropping a page into a slide deck that prefers images",
      "Sharing a page in apps that reject PDF attachments",
      "Making simple thumbnails of a short document",
    ],
    tipsTitle: "Quality notes",
    tips: [
      "For the reverse task, use JPG to PDF to combine images back into a document.",
      "Very large or dense pages produce larger JPG files.",
      "Password-protected PDFs need to be unlocked first.",
    ],
    privacy: privacyNote,
    related: ["/jpg-to-pdf", "/split-pdf", "/merge-pdf"],
    faqs: [
      { question: "How do I convert PDF to JPG?", answer: "Upload a PDF and choose Convert PDF to JPG. Download the JPG or ZIP of images when rendering finishes." },
      { question: "Does every page become an image?", answer: "Yes. Each page is rendered to its own JPG file." },
      { question: "What if my PDF has one page?", answer: "You receive a single .jpg file instead of a ZIP." },
      { question: "Is this the same as renaming the file?", answer: "No. Pages are drawn as images. The download is a JPEG (or a ZIP of JPEGs)." },
      { question: "Can I convert PDF to an image for social posts?", answer: "Yes. JPG pages are often easier to upload than a PDF, though you should check any size limits on the destination." },
      { question: "Will text stay selectable?", answer: "No. JPG is a picture of the page, so the text is not selectable." },
      { question: "What is the page limit?", answer: "Up to 40 pages and 25 MB per PDF." },
    ],
  },
};

export const documentToolList = Object.values(documentTools);

export default documentTools;
