const imageToPdfToolContent = {
  jpg: {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    path: "/jpg-to-pdf",
    formats: "JPG and JPEG (.jpg, .jpeg)",
    guideTitle: "Create one PDF from your JPG images",
    introduction: "Use the JPG to PDF converter when you want to put photos, scanned pages, or saved images into one document that is easier to share, print, or upload.",
    useCaseIntro: "JPG is a common photo format, so this tool is useful whenever a group of images needs to become a single document.",
    useCases: ["Combining photographed notes or receipts into one file", "Preparing image attachments for an application or upload", "Keeping a sequence of scanned pages in the right order"],
    steps: [
      { title: "Add JPG images", description: "Choose one or more JPG files from your device or drag them into the upload area." },
      { title: "Check the sequence", description: "Review the preview cards and drag images to the order you need." },
      { title: "Create the PDF", description: "Select the conversion button to turn the chosen images into one PDF." },
      { title: "Save the result", description: "Download the generated PDF to your device when it is ready." },
    ],
    faqs: [
      { question: "Can I combine multiple JPG images into one PDF?", answer: "Yes. Add up to 20 JPG or JPEG images, arrange them, and create one PDF." },
      { question: "Can I change the page order?", answer: "Yes. Drag the preview cards before conversion to set the page order." },
      { question: "What JPG files are accepted?", answer: "The converter accepts .jpg and .jpeg files, with a maximum file size of 10 MB for each image." },
      { question: "Do I need to install an app?", answer: "No. The converter runs in a web browser and does not require an account or software installation." },
    ],
  },
  png: {
    id: "png-to-pdf",
    name: "PNG to PDF",
    path: "/png-to-pdf",
    formats: "PNG (.png)",
    guideTitle: "Put PNG screenshots and graphics into a PDF",
    introduction: "The PNG to PDF converter helps turn screenshots, diagrams, and exported graphics into one shareable document without having to place every image in a separate file.",
    useCaseIntro: "PNG is commonly used for screenshots and graphics where clear edges and text matter, making it useful for visual records and reference documents.",
    useCases: ["Combining screenshots for a bug report or support request", "Sharing a set of diagrams or UI mockups as one document", "Preparing image-based instructions for printing or review"],
    steps: [
      { title: "Upload PNG files", description: "Choose one or more PNG screenshots or graphics from your device." },
      { title: "Review every image", description: "Use the previews to make sure the images are present and in the needed order." },
      { title: "Convert to PDF", description: "Select the conversion button to create a single PDF document." },
      { title: "Download your file", description: "Save the generated PDF to your device after processing finishes." },
    ],
    faqs: [
      { question: "Can I combine screenshots into one PDF?", answer: "Yes. Upload several PNG screenshots and arrange them before creating one PDF." },
      { question: "Will the PNG files stay in the order I upload them?", answer: "You can review and change the order with the drag controls before conversion." },
      { question: "How many PNG files can I add?", answer: "You can add up to 20 PNG files in one conversion, with a 10 MB limit per image." },
      { question: "Is this useful for transparent PNGs?", answer: "You can upload PNG files, but the final PDF page uses a white background behind the image." },
    ],
  },
  jpeg: {
    id: "jpeg-to-pdf",
    name: "JPEG to PDF",
    path: "/jpeg-to-pdf",
    formats: "JPEG and JPG (.jpeg, .jpg)",
    guideTitle: "Convert JPEG photo files into a PDF document",
    introduction: "Use the JPEG to PDF converter to collect camera images or downloaded JPEGs in a single document, rather than sending each photo as a separate attachment.",
    useCaseIntro: "This page is helpful when your files use the .jpeg extension, which is another common filename extension for JPEG images.",
    useCases: ["Creating a PDF from camera photos saved as .jpeg", "Collecting document photos before sending them by email", "Saving a visual record as one ordered document"],
    steps: [
      { title: "Select JPEG images", description: "Upload one or more .jpeg or .jpg image files from your device." },
      { title: "Arrange the pages", description: "Use the preview cards to confirm and adjust the image sequence." },
      { title: "Generate the PDF", description: "Select the conversion button when the images are ready." },
      { title: "Download the document", description: "Save the generated PDF from your browser." },
    ],
    faqs: [
      { question: "Is JPEG different from JPG for this tool?", answer: "Both are JPEG image files. This converter accepts both .jpeg and .jpg files." },
      { question: "Can I add more than one JPEG image?", answer: "Yes. Add up to 20 images and create one PDF with one image on each page." },
      { question: "Can I rearrange JPEG pages?", answer: "Yes. Drag the image previews into the required order before converting." },
      { question: "Do I need an account to convert JPEG files?", answer: "No account or software installation is required to use the converter." },
    ],
  },
  webp: {
    id: "webp-to-pdf",
    name: "WEBP to PDF",
    path: "/webp-to-pdf",
    formats: "WEBP (.webp)",
    guideTitle: "Make a PDF from WEBP images",
    introduction: "The WEBP to PDF converter is designed for images saved from modern websites and browsers. It lets you put those WEBP files into a more widely shareable PDF document.",
    useCaseIntro: "WEBP is often used for web images. Converting it to PDF can make a set of reference images easier to send, review, or print together.",
    useCases: ["Combining WEBP reference images from a web project", "Creating a printable document from saved web graphics", "Sending several WEBP images as one attachment"],
    steps: [
      { title: "Upload WEBP images", description: "Choose one or more .webp files from your device." },
      { title: "Set the image order", description: "Review the previews and drag images into the sequence you need." },
      { title: "Convert the images", description: "Create a single PDF from the selected WEBP files." },
      { title: "Download the PDF", description: "Save the completed PDF to your device." },
    ],
    faqs: [
      { question: "Can I convert WEBP images to one PDF?", answer: "Yes. Upload up to 20 WEBP images and create one PDF document." },
      { question: "Why would I convert WEBP to PDF?", answer: "A PDF can be more convenient when you need to share several images as one document or print them together." },
      { question: "Can I reorder WEBP files before converting?", answer: "Yes. Drag the preview cards to set the final page order." },
      { question: "What is the maximum WEBP file size?", answer: "Each uploaded image can be up to 10 MB." },
    ],
  },
};

export default imageToPdfToolContent;
