const imageToPdfToolContent = {
  jpg: {
    id: "jpg-to-pdf",
    name: "JPG to PDF",
    shortName: "JPG",
    path: "/jpg-to-pdf",
    formats: "JPG and JPEG (.jpg, .jpeg)",
    guideTitle: "Create one PDF from your JPG images",
    introduction: "Convert multiple JPG or JPEG images into one ordered PDF online. Upload up to 20 photos, scanned pages, or saved images, drag them into the right sequence, and download one document for sharing, printing, or uploading.",
    useCaseIntro: "JPG is a common photo format, so this tool is useful whenever a group of images needs to become a single document.",
    useCases: ["Combining photographed notes or receipts into one file", "Preparing image attachments for an application or upload", "Keeping a sequence of scanned pages in the right order"],
    formatNotes: "JPG is a practical choice for photographs, camera scans, and receipts. It is usually already the format produced by a phone camera, so no format change is needed before making the PDF.",
    tips: ["Photograph pages in even light so text stays readable.", "Put photos in reading order before conversion.", "For multi-page paperwork, use Document Scanner when you want trim, modes, or page numbers."],
    problems: ["If a photo is sideways, rotate it on your device before uploading.", "If text is hard to read, retake the photo closer and in better light.", "If a file is rejected, confirm it is a JPG/JPEG under 10 MB."],
    steps: [
      { title: "Add JPG images", description: "Choose one or more JPG files from your device or drag them into the upload area." },
      { title: "Check the sequence", description: "Review the preview cards and drag images to the order you need." },
      { title: "Create the PDF", description: "Select the conversion button to turn the chosen images into one PDF." },
      { title: "Save the result", description: "Download the generated PDF to your device when it is ready." },
    ],
    faqs: [
      { question: "Can I combine multiple JPG images into one PDF?", answer: "Yes. Add up to 20 JPG or JPEG images, arrange them, and create one A4 PDF." },
      { question: "Can I change the page order?", answer: "Yes. Drag the preview cards before conversion to set the page order." },
      { question: "What happens to photos that are not A4 shaped?", answer: "Each image is scaled to fit an A4 page and centered. Extra space shows as margin; the tool does not crop to fill the sheet." },
      { question: "Is text in the photos made searchable?", answer: "No. JPG to PDF places pictures on pages. It does not run OCR. Use Document Scanner for paper cleanup, then PDF to Word with OCR if you need editable text." },
      { question: "When should I use Document Scanner instead?", answer: "When you photographed forms or notes and need edge trim, grayscale or black-and-white, page numbers, or a size goal." },
      { question: "What is the size limit?", answer: "Each image can be up to 10 MB, with a maximum of 20 files." },
      { question: "Do I need to install an app?", answer: "No. The converter runs in a web browser and does not require an account." },
    ],
  },
  png: {
    id: "png-to-pdf",
    name: "PNG to PDF",
    shortName: "PNG",
    path: "/png-to-pdf",
    formats: "PNG (.png)",
    guideTitle: "Put PNG screenshots and graphics into a PDF",
    introduction: "Convert multiple PNG images into one PDF online. Add up to 20 screenshots, diagrams, or exported graphics, arrange their order with drag and drop, and download a single shareable document.",
    useCaseIntro: "PNG is commonly used for screenshots and graphics where clear edges and text matter, making it useful for visual records and reference documents.",
    useCases: ["Combining screenshots for a bug report or support request", "Sharing a set of diagrams or UI mockups as one document", "Preparing image-based instructions for printing or review"],
    formatNotes: "PNG is commonly used for screenshots, diagrams, and graphics because edges and interface text can stay crisp. Transparent areas are placed on a white PDF page.",
    tips: ["Use the original screenshot rather than a compressed copy when small text matters.", "Review each preview to keep screenshots in the order of the workflow.", "Choose Resize Image first if the screenshots need matching dimensions."],
    problems: ["Transparent areas will appear against white in the PDF.", "Very large screenshots may be easier to read if split into separate images.", "If a PNG is over 10 MB, resize it before uploading."],
    steps: [
      { title: "Upload PNG files", description: "Choose one or more PNG screenshots or graphics from your device." },
      { title: "Review every image", description: "Use the previews to make sure the images are present and in the needed order." },
      { title: "Convert to PDF", description: "Select the conversion button to create a single PDF document." },
      { title: "Download your file", description: "Save the generated PDF to your device after processing finishes." },
    ],
    faqs: [
      { question: "Can I combine screenshots into one PDF?", answer: "Yes. Upload several PNG screenshots and arrange them before creating one A4 PDF." },
      { question: "What happens to transparent areas?", answer: "Transparent pixels are drawn on a white PDF page. You cannot keep a transparent background in the download." },
      { question: "Will small UI text stay sharp?", answer: "PNG keeps crisp edges better than a heavily compressed JPG, but a huge screenshot is still fitted onto A4, so tiny labels can shrink. Resize first if you need a consistent width." },
      { question: "How many PNG files can I add?", answer: "Up to 20 PNG files, 10 MB each." },
      { question: "Is this a vector PDF of a diagram?", answer: "No. The PNG remains a bitmap placed on the page." },
      { question: "Can I drag and drop PNG files?", answer: "Yes. Drop PNG images into the upload area, then use the preview cards to set the page sequence." },
    ],
  },
  jpeg: {
    id: "jpeg-to-pdf",
    name: "JPEG to PDF",
    shortName: "JPEG",
    path: "/jpeg-to-pdf",
    formats: "JPEG and JPG (.jpeg, .jpg)",
    guideTitle: "Convert JPEG photo files into a PDF document",
    introduction: "Convert multiple JPEG or JPG images into one PDF online. Upload up to 20 camera photos or downloaded images, set their order with drag and drop, and create one document instead of sending separate attachments.",
    useCaseIntro: "This page is helpful when your files use the .jpeg extension, which is another common filename extension for JPEG images.",
    useCases: ["Creating a PDF from camera photos saved as .jpeg", "Collecting document photos before sending them by email", "Saving a visual record as one ordered document"],
    formatNotes: "JPEG and JPG describe the same image format; the different extension is usually a camera, device, or export preference. This page accepts either extension.",
    tips: ["Use this tool when files are labelled .jpeg or .jpg—both are accepted.", "Keep a consistent orientation across camera photos for a neater document.", "For photographed paperwork that needs cleanup, use the Document Scanner."],
    problems: ["A .jpeg filename is accepted just like .jpg.", "If images are out of sequence, drag the preview cards into order before creating the PDF.", "If a camera image exceeds 10 MB, reduce its size first."],
    steps: [
      { title: "Select JPEG images", description: "Upload one or more .jpeg or .jpg image files from your device." },
      { title: "Arrange the pages", description: "Use the preview cards to confirm and adjust the image sequence." },
      { title: "Generate the PDF", description: "Select the conversion button when the images are ready." },
      { title: "Download the document", description: "Save the generated PDF from your browser." },
    ],
    faqs: [
      { question: "Is JPEG different from JPG for this tool?", answer: "Both are the JPEG image codec. This page accepts .jpeg and .jpg. The layout is A4, same as JPG to PDF; this page is written for camera and export files that use the longer extension." },
      { question: "Can I mix .jpeg and .jpg in one PDF?", answer: "Yes. Add up to 20 images and set the order with the previews." },
      { question: "Does the converter auto-rotate camera shots?", answer: "No. Rotate sideways photos on your device before uploading." },
      { question: "Can I rearrange JPEG pages?", answer: "Yes. Drag the image previews into the required order before converting." },
      { question: "What is the size limit?", answer: "10 MB per image, 20 images per PDF." },
      { question: "Do I need an account?", answer: "No account or extra software is required." },
    ],
  },
  webp: {
    id: "webp-to-pdf",
    name: "WEBP to PDF",
    shortName: "WEBP",
    path: "/webp-to-pdf",
    formats: "WEBP (.webp)",
    guideTitle: "Make a PDF from WEBP images",
    introduction: "Convert multiple WEBP images into one PDF online. Upload up to 20 images saved from websites or browsers, arrange them in the needed order, and create a more easily shared or printable PDF document.",
    useCaseIntro: "WEBP is often used for web images. Converting it to PDF can make a set of reference images easier to send, review, or print together.",
    useCases: ["Combining WEBP reference images from a web project", "Creating a printable document from saved web graphics", "Sending several WEBP images as one attachment"],
    formatNotes: "WEBP is widely used for browser-delivered images. A PDF is useful when several saved web graphics need to be reviewed, printed, or shared as one document.",
    tips: ["Save the original WEBP files from your browser before uploading.", "Check the previews because web images may have different orientations or dimensions.", "Use Resize Image first when a batch needs a consistent output size."],
    problems: ["If a downloaded image is not a WEBP file, use the matching image-to-PDF tool instead.", "Animated WEBP is not presented as a multi-frame document; use a still image where a single page is needed.", "If an image is over 10 MB, resize it before conversion."],
    steps: [
      { title: "Upload WEBP images", description: "Choose one or more .webp files from your device." },
      { title: "Set the image order", description: "Review the previews and drag images into the sequence you need." },
      { title: "Convert the images", description: "Create a single PDF from the selected WEBP files." },
      { title: "Download the PDF", description: "Save the completed PDF to your device." },
    ],
    faqs: [
      { question: "Can I convert WEBP images to one PDF?", answer: "Yes. Upload up to 20 still WEBP images and create one A4 PDF." },
      { question: "Why convert WEBP instead of keeping the files?", answer: "Some printers and older apps still do not open WEBP. A PDF is a more common attachment for a sequence of stills." },
      { question: "What about animated WEBP?", answer: "Animation is not expanded into a page per frame. Use a still image when you need one document page." },
      { question: "Can I reorder WEBP files before converting?", answer: "Yes. Drag the preview cards to set the final page order." },
      { question: "What is the maximum WEBP file size?", answer: "Each uploaded image can be up to 10 MB." },
      { question: "Should I convert to JPG first?", answer: "Not for this tool. It accepts WEBP directly." },
    ],
  },
};

export default imageToPdfToolContent;
