export const pdfGuides = [
  {
    slug: "how-to-convert-jpg-to-pdf",
    title: "How to convert JPG photos to one PDF",
    description: "A practical way to arrange photographed pages, receipts, or images into one PDF.",
    tool: "/jpg-to-pdf",
    toolName: "JPG to PDF",
    intro: "A PDF is easier to upload or share than a run of separate photos. Start with clear JPG or JPEG files, then make the page order match the order someone should read them.",
    steps: ["Choose JPG or JPEG photos that are upright and readable.", "Open JPG to PDF, add up to 20 files, and use the previews to check the sequence.", "Drag previews into reading order, create the PDF, and download it."],
    tips: ["Use even lighting for document photos.", "Retake blurry pages before conversion.", "Use Document Scanner when you need trimming, scan modes, or page numbers."],
    relatedGuides: ["how-to-convert-png-to-pdf", "how-to-scan-document-photos-to-pdf", "how-to-convert-pdf-to-jpg"],
  },
  {
    slug: "how-to-convert-png-to-pdf",
    title: "How to turn PNG screenshots into a PDF",
    description: "Prepare screenshots, diagrams, and interface images for one readable PDF document.",
    tool: "/png-to-pdf",
    toolName: "PNG to PDF",
    intro: "PNG works well for screenshots and diagrams. Combining them into a PDF is useful for a support ticket, design review, or a step-by-step record.",
    steps: ["Collect the final screenshots and make sure sensitive information is removed.", "Upload up to 20 PNGs to PNG to PDF and order them as the workflow happened.", "Create the PDF and review the downloaded file before sending it."],
    tips: ["PNG transparency is placed over white in the PDF.", "Keep screenshots at a legible size.", "Resize a batch first if the images need consistent dimensions."],
    relatedGuides: ["how-to-convert-jpg-to-pdf", "how-to-resize-multiple-images"],
  },
  {
    slug: "how-to-scan-document-photos-to-pdf",
    title: "How to scan document photos into a PDF",
    description: "Create a cleaner multi-page PDF from phone photos with the available scanner controls.",
    tool: "/document-scanner",
    toolName: "Document Scanner",
    intro: "Document Scanner helps turn up to 20 photographed pages into an A4 PDF. It is intended for papers such as forms, notes, and certificates—not as a replacement for reviewing the original document.",
    steps: ["Photograph each page flat, in good light, with all text visible.", "Upload JPG, PNG, or WEBP photos and review the preview and any blank or blurry warnings.", "Choose white-edge trimming, a color mode, rotation, page numbers, and a size goal, then create the PDF."],
    tips: ["Use grayscale or black-and-white for text-heavy pages when appropriate.", "A size goal adjusts image quality; final size depends on the pages.", "Preview every photo before creating the PDF."],
    relatedGuides: ["how-to-convert-jpg-to-pdf", "how-to-convert-scanned-pdf-to-word"],
  },
  {
    slug: "how-to-package-multiple-pdfs-into-a-zip",
    title: "How to package multiple PDFs in a ZIP file",
    description: "Send several unchanged PDFs as one downloadable archive.",
    tool: "/pdf-to-zip",
    toolName: "PDF to ZIP",
    intro: "A ZIP archive keeps several PDFs together while leaving their PDF pages and contents unchanged. It is useful for related forms, invoices, or project documents.",
    steps: ["Gather up to 20 PDFs, each no larger than 25 MB.", "Add them to PDF to ZIP, remove anything that should not be included, and choose an archive filename.", "Create and download the ZIP, then open it locally to verify the contents."],
    tips: ["ZIP packaging does not promise a smaller total size.", "Use descriptive PDF filenames before packaging.", "Create photo PDFs first with an image-to-PDF tool if needed."],
    relatedGuides: ["how-to-merge-pdf-files", "how-to-split-a-pdf"],
  },
  {
    slug: "how-to-resize-multiple-images",
    title: "How to resize multiple images without stretching",
    description: "Use pixels or percentage settings to prepare a batch of image files for upload or sharing.",
    tool: "/resize-image",
    toolName: "Resize Image",
    intro: "Resizing changes image dimensions; it is not the same as cropping. QuickPDFHD can resize up to 20 JPG, PNG, or WEBP images and returns the batch in a ZIP archive.",
    steps: ["Add up to 20 images, each under 10 MB and no more than 8000 px in either dimension.", "Use Pixels with aspect-ratio lock on so width and height stay proportional, or Percentage to scale each file by the same amount.", "Unlock aspect ratio only when you want exact width and height and are willing to stretch the image, then download the ZIP."],
    tips: ["Keep the lock on to avoid crop, stretch, and extra white bars.", "JPG and WEBP have a quality control; PNG does not.", "DPI metadata is separate from pixel width and height."],
    relatedGuides: ["how-to-convert-jpg-to-pdf", "how-to-convert-png-to-pdf"],
  },
  {
    slug: "how-to-convert-word-to-pdf",
    title: "How to convert Word to PDF",
    seoTitle: "How to Convert Word to PDF Online | QuickPDFHD",
    description: "Turn a DOC or DOCX file into a PDF you can print, attach, or upload without needing Word on the other computer.",
    tool: "/word-to-pdf",
    toolName: "Word to PDF",
    intro: "People convert Word to PDF when a letter, report, or resume should travel as a finished document. Recipients can open a PDF without Microsoft Word, and the pages are less likely to reflow the way a .docx file can.",
    why: "Use Word to PDF when you wrote the file in Word and now need something stable for email, a job portal, or printing. The converter reads the uploaded DOC or DOCX and builds a PDF from the document text, headings, lists, tables, and common embedded images.",
    formats: "Input: .doc and .docx, one file up to 15 MB. Output: a PDF download.",
    steps: [
      "Finish the Word file. Save as .docx when you can; older .doc files are accepted but often keep less layout.",
      "Open Word to PDF and upload one document. Conversion runs on the server, not as a renamed file extension.",
      "Download the PDF and check headings, lists, tables, and images before you send it.",
    ],
    limitations: [
      "Unusual fonts, text boxes, macros, and heavy Word themes may look simpler in the PDF.",
      "Tracked changes and comments are not a dedicated review mode; convert a clean copy if you only want the visible text.",
      "Password-protected Word files are not converted until they are unlocked.",
    ],
    tips: [
      "DOCX usually preserves more structure than a very old .doc file.",
      "If you later need an editable file, use PDF to Word on a text-based PDF.",
      "If special characters show as question marks, those characters were outside the text encoding used for this converter.",
    ],
    problems: [
      "If layout looks different, the converter simplified the Word theme. Check the PDF rather than assuming pixel-perfect design.",
      "If conversion is rejected, confirm the file is .doc or .docx and under 15 MB.",
    ],
    faqs: [
      { question: "Can I convert DOCX to PDF in a browser?", answer: "Yes. Upload a .docx file on Word to PDF and download the generated PDF. No Microsoft Word install is required on your device." },
      { question: "Does this work with older .doc files?", answer: "Yes. Legacy .doc files are accepted. The PDF is built from extracted document content, so layout may be simpler than in Word." },
      { question: "Will every Word style be preserved?", answer: "Headings, paragraphs, lists, tables, and common images are included. Custom themes, floating graphics, and unusual fonts may not match Word exactly." },
      { question: "Is the PDF editable?", answer: "The download is a PDF, not a Word file. To edit text later, keep your original .docx or use PDF to Word on a selectable-text PDF." },
      { question: "Is there a size limit?", answer: "Each Word file can be up to 15 MB." },
    ],
    relatedGuides: ["how-to-convert-pdf-to-word", "how-to-convert-excel-to-pdf", "how-to-merge-pdf-files"],
  },
  {
    slug: "how-to-convert-pdf-to-word",
    title: "How to convert PDF to Word",
    seoTitle: "How to Convert PDF to Word (DOCX) | QuickPDFHD",
    description: "Extract selectable PDF text into an editable DOCX file. Use NO OCR for digital PDFs; use OCR only when the pages are scans.",
    tool: "/pdf-to-word",
    toolName: "PDF to Word",
    intro: "PDF to Word is useful when you need paragraphs from a PDF in a file you can edit. The right mode depends on whether you can already highlight text in a PDF viewer.",
    why: "Choose NO OCR when the PDF already stores text—files exported from Word, Excel, or a text editor. That path copies the stored text into a DOCX file and is usually faster. Choose OCR only when pages are pictures of text, which is covered in the scanned-PDF guide.",
    formats: "Input: one PDF up to 25 MB. NO OCR accepts up to 40 pages. Output: a .docx Word file.",
    steps: [
      "Open the PDF on your computer and try to select a sentence. If you can highlight words, NO OCR is the better starting point.",
      "Open PDF to Word, upload the file, and leave the mode on NO OCR.",
      "Convert and open the DOCX. Edit the text in Word or another editor that supports .docx.",
    ],
    limitations: [
      "Columns and tables often become sequential lines rather than a perfect Word table.",
      "Fonts, headers, and exact page design are not rebuilt.",
      "Encrypted PDFs need to be unlocked first.",
      "If there is no selectable text, NO OCR cannot invent it—use OCR instead.",
    ],
    tips: [
      "Keep native PDFs from Word or a text export when you can; they convert more reliably than photos of paper.",
      "Check tables after conversion.",
      "If the tool reports no selectable text, switch to OCR or see the scanned PDF guide.",
    ],
    problems: [
      "Empty or image-only PDFs fail in NO OCR by design.",
      "Garbled column order usually means the PDF stored text in drawing order, not reading order.",
    ],
    faqs: [
      { question: "What is the difference between NO OCR and OCR?", answer: "NO OCR copies text already stored in the PDF. OCR reads characters from a rendered image of each page. Use NO OCR when you can already select text." },
      { question: "Will I get a real Word file?", answer: "Yes. The download is a standard .docx file, not a renamed PDF." },
      { question: "Can I convert PDF to Word without OCR?", answer: "Yes. NO OCR is the default and is the better choice for selectable-text PDFs." },
      { question: "Does formatting stay the same?", answer: "You get editable paragraphs in page order. Complex layout usually needs cleanup in Word." },
      { question: "What is the page limit for NO OCR?", answer: "NO OCR accepts PDFs of up to 40 pages and 25 MB." },
      { question: "What if my PDF is a scan?", answer: "Use OCR mode, or follow the scanned PDF to Word guide." },
    ],
    relatedGuides: ["how-to-convert-scanned-pdf-to-word", "how-to-convert-word-to-pdf", "how-to-convert-pdf-to-excel"],
  },
  {
    slug: "how-to-convert-scanned-pdf-to-word",
    title: "How to convert a scanned PDF to Word with OCR",
    seoTitle: "Convert Scanned PDF to Word with OCR | QuickPDFHD",
    description: "Use OCR when a PDF is a scan or image-only file. Learn when OCR is needed, which language to pick, and what accuracy to expect.",
    tool: "/pdf-to-word",
    toolName: "PDF to Word",
    intro: "A scanned PDF is usually a picture of each page. You cannot highlight the words in a normal PDF viewer, so copying text does not work. OCR (optical character recognition) reads those pictures and writes recognized characters into a Word file.",
    why: "NO OCR only works when the PDF already contains text objects. Camera scans, photocopies, and “print to PDF” files that flattened pages into images need OCR. QuickPDFHD runs Tesseract on the server. You can set the language to English, Hindi, or English + Hindi. Recognition still depends on how clear the scan is.",
    formats: "Input: one scanned or image-only PDF up to 25 MB and 15 pages in OCR mode. Output: a .docx file with recognized text in page order.",
    steps: [
      "Confirm the PDF is a scan: try to select text. If nothing highlights, use OCR.",
      "Open PDF to Word, upload the file, choose OCR, and pick English, Hindi, or English + Hindi to match the page.",
      "Wait for recognition to finish, then open the DOCX and correct any misread words.",
    ],
    limitations: [
      "OCR does not rebuild columns, fonts, or exact positions. You get paragraph-like lines in page order.",
      "Handwriting, blur, heavy rotation, low contrast, stamps, and complex tables often reduce accuracy.",
      "The selected language must reach the OCR engine. If a language model cannot load, the tool shows an error instead of silently using English.",
      "OCR is limited to 15 pages because recognition is slower and more demanding than text extraction.",
    ],
    tips: [
      "Use a high-contrast, upright scan when you can.",
      "Pick Hindi or English + Hindi only when the page actually contains that script.",
      "Review names, numbers, and legal wording before you rely on the Word file.",
    ],
    problems: [
      "If NO OCR says no selectable text, that is expected for a scan—switch to OCR.",
      "If Hindi looks wrong, confirm you selected Hindi or English + Hindi, and that the scan is sharp enough to read by eye.",
      "Rotated pages can still confuse recognition even after automatic orientation retries.",
    ],
    faqs: [
      { question: "Why doesn’t copy-paste work on my PDF?", answer: "The pages are probably images. There is no stored text to copy. OCR is the path that reads those images." },
      { question: "Does OCR make scanned PDF text editable?", answer: "OCR writes recognized characters into a DOCX file you can edit. It does not recreate the original page design." },
      { question: "Can OCR read Hindi?", answer: "Yes, when you set the OCR language to Hindi or English + Hindi. Accuracy still depends on scan quality." },
      { question: "Should I use English + Hindi for every file?", answer: "No. Use the combined option when the page mixes both scripts. A single-language page is usually clearer with one language selected." },
      { question: "Is OCR accurate for every scan?", answer: "No. Poor photos, handwriting, and dense tables often need manual correction." },
      { question: "What is the OCR page limit?", answer: "OCR accepts up to 15 pages and 25 MB." },
      { question: "Does OCR run if I leave NO OCR selected?", answer: "No. Tesseract runs only when you choose OCR." },
    ],
    relatedGuides: ["how-to-convert-pdf-to-word", "how-to-scan-document-photos-to-pdf", "how-to-convert-pdf-to-jpg"],
  },
  {
    slug: "how-to-convert-excel-to-pdf",
    title: "How to convert Excel to PDF",
    seoTitle: "How to Convert Excel to PDF (XLS, XLSX) | QuickPDFHD",
    description: "Share worksheet tables as a printable landscape PDF. Charts and macros are not rendered as Excel objects.",
    tool: "/excel-to-pdf",
    toolName: "Excel to PDF",
    intro: "Excel to PDF is for when a spreadsheet should be read or printed as a document, not opened as a workbook. The converter reads worksheet cells and draws them as tables on PDF pages.",
    why: "Use it for price lists, attendance sheets, and simple reports that need to stay in rows and columns. People who do not use Excel can still open the PDF.",
    formats: "Input: one .xls or .xlsx file up to 15 MB. Output: a landscape PDF of worksheets that contain data.",
    steps: [
      "Clean the workbook so the tables you care about are visible. Hidden sheets without data are skipped.",
      "Open Excel to PDF and upload one spreadsheet.",
      "Download the PDF and check column wrapping, page breaks, and whether every intended sheet is present.",
    ],
    limitations: [
      "Charts, macros, pivot caches, and Excel drawings are not rendered as live Excel objects.",
      "Very wide sheets may wrap or continue on following pages.",
      "This is a table-oriented conversion, not a pixel-perfect Excel print preview.",
    ],
    tips: [
      "Put one logical table per sheet when you can.",
      "If you need an editable grid later, keep the original workbook or use PDF to Excel on a text-based table PDF.",
    ],
    problems: [
      "Empty workbooks produce no useful PDF.",
      "If a sheet is missing, it may have had no cell data the converter could read.",
    ],
    faqs: [
      { question: "Can I convert XLSX to PDF online?", answer: "Yes. Upload an .xlsx or .xls file and download a PDF of the worksheet tables." },
      { question: "Are charts included?", answer: "No. The converter draws cell values as tables. Charts and macros are not exported as Excel objects." },
      { question: "Do I need Excel installed?", answer: "No. Conversion happens through the web tool." },
      { question: "What is the file size limit?", answer: "15 MB per workbook." },
      { question: "Will formulas stay editable?", answer: "No. The PDF shows calculated or stored cell values as a document, not a live spreadsheet." },
    ],
    relatedGuides: ["how-to-convert-pdf-to-excel", "how-to-convert-word-to-pdf"],
  },
  {
    slug: "how-to-convert-pdf-to-excel",
    title: "How to convert PDF to Excel",
    seoTitle: "How to Convert PDF to Excel (XLSX) | QuickPDFHD",
    description: "Extract table-like text from a PDF into an XLSX spreadsheet. Scanned PDFs without selectable text will not produce a usable grid.",
    tool: "/pdf-to-excel",
    toolName: "PDF to Excel",
    intro: "PDF to Excel looks for text that is already stored in the PDF and groups it into rows. It is meant for digital table PDFs, not for photographs of spreadsheets.",
    why: "Use it when a report was issued as a PDF but you need the numbers in Excel. If you cannot select cells or text in the PDF, this tool cannot invent a grid from pixels.",
    formats: "Input: one PDF up to 25 MB and 40 pages. Output: an .xlsx workbook with a sheet per PDF page that contains table-like text.",
    steps: [
      "Check that you can select text in the PDF. If not, the file is likely a scan and will not extract as a table.",
      "Open PDF to Excel, upload the file, and start extraction.",
      "Open the XLSX and verify columns. Merged cells and multi-line headers often need cleanup.",
    ],
    limitations: [
      "There is no OCR path on PDF to Excel. Image-only PDFs cannot be turned into spreadsheets here.",
      "Complex multi-column layouts may land in the wrong columns.",
      "Charts become nothing unless they also exist as selectable text.",
    ],
    tips: [
      "Native PDFs exported from Excel convert more cleanly than printed-and-scanned sheets.",
      "If you only need a picture of a table, use PDF to JPG instead.",
    ],
    problems: [
      "If the tool finds no table-like text, use a digital PDF or recreate the table by hand.",
      "Misaligned columns usually mean the PDF did not store a true table structure.",
    ],
    faqs: [
      { question: "Can I convert a scanned PDF to Excel?", answer: "Not with this tool. It extracts selectable text only. Scanned tables need a different workflow, such as OCR to Word and then manual cleanup." },
      { question: "Do I get a real XLSX file?", answer: "Yes. The download is an Excel workbook, not a CSV rename of the PDF." },
      { question: "Are formulas recovered?", answer: "No. You get text and numbers as they appeared, not the original Excel formulas." },
      { question: "What is the page limit?", answer: "Up to 40 pages and 25 MB." },
      { question: "Will every column line up?", answer: "Simple row-and-column text usually fares better than nested headers or mixed layouts." },
    ],
    relatedGuides: ["how-to-convert-excel-to-pdf", "how-to-convert-pdf-to-word", "how-to-convert-scanned-pdf-to-word"],
  },
  {
    slug: "how-to-split-a-pdf",
    title: "How to split a PDF",
    seoTitle: "How to Split a PDF Online | QuickPDFHD",
    description: "Extract a page range, save each page as its own PDF, or split a long file into smaller chunks without flattening pages into images.",
    tool: "/split-pdf",
    toolName: "Split PDF",
    intro: "Splitting copies pages from a source PDF into new files. The original upload stays on your device. Vector text and existing page sizes are preserved because pages are not converted to photos.",
    why: "Use Split PDF when a reviewer only needs a chapter, when certificates arrived as one scan, or when a handbook is too large to email whole.",
    formats: "Input: one PDF up to 25 MB and 200 pages. Output: one PDF for an extract range, or a ZIP of PDFs for separate pages or chunks.",
    steps: [
      "Upload the PDF on Split PDF.",
      "Choose Extract range (for example 1-4, 9), Separate pages, or chunks with a page count you choose.",
      "Download the PDF or ZIP and confirm the pages are the ones you expected.",
    ],
    limitations: [
      "Page numbers follow the file order, which may differ from printed page numbers.",
      "Encrypted PDFs cannot be split until the password is removed.",
      "Splitting does not redact content; it only copies the pages you asked for.",
    ],
    tips: [
      "Leave the range blank in separate-pages or extract mode to use every page.",
      "If you need those extracts in one packet later, use Merge PDF.",
      "If you only need to send several unchanged files together, PDF to ZIP may be enough.",
    ],
    problems: [
      "If the wrong pages appear, the PDF’s internal order may not match the printed numbers.",
      "If the file is rejected, check the 25 MB and 200-page limits.",
    ],
    faqs: [
      { question: "How do I extract specific pages?", answer: "Choose Extract range and enter pages such as 1-4, 9. You receive one new PDF." },
      { question: "How do I split a PDF into single pages?", answer: "Choose Separate pages. The download is a ZIP with one PDF per selected page." },
      { question: "Is the original PDF changed?", answer: "No. A new file is generated. Your original stays on your device unless you overwrite it yourself." },
      { question: "Are pages turned into images?", answer: "No. Existing PDF pages are copied." },
      { question: "Can I split a large PDF?", answer: "Yes, within 25 MB and 200 pages. Chunk mode creates several smaller PDFs." },
    ],
    relatedGuides: ["how-to-merge-pdf-files", "how-to-package-multiple-pdfs-into-a-zip", "how-to-convert-pdf-to-jpg"],
  },
  {
    slug: "how-to-merge-pdf-files",
    title: "How to merge PDF files",
    seoTitle: "How to Merge PDF Files Online | QuickPDFHD",
    description: "Combine two or more PDFs in the order you choose. Pages are copied, not photographed, so existing text stays as PDF content.",
    tool: "/merge-pdf",
    toolName: "Merge PDF",
    intro: "Merging is a document-organization task. Instead of attaching five files, you attach one PDF that already contains them in reading order.",
    why: "Use it for application packets, monthly report bundles, or signed forms that belong together. Each source page is copied into the new file. Mixed page sizes stay as they were.",
    formats: "Input: 2 to 20 PDF files, each up to 25 MB, with a combined limit of 200 pages. Output: one merged PDF.",
    steps: [
      "Add at least two PDFs on Merge PDF.",
      "Move files up or down so chapters, invoices, or forms appear in the right sequence.",
      "Merge and download the combined document, then flip through it once before sending.",
    ],
    limitations: [
      "The tool does not add a table of contents or redesign layouts.",
      "Password-protected files must be unlocked first.",
      "If you only need some pages, split first, then merge.",
    ],
    tips: [
      "Rename files so the list is easy to check.",
      "Merging does not recompress pages as images.",
      "For several files that should stay separate, use PDF to ZIP.",
    ],
    problems: [
      "If order is wrong, use the move controls before merging again.",
      "If a file is skipped, confirm it is a valid, unencrypted PDF under 25 MB.",
    ],
    faqs: [
      { question: "Can I combine more than two PDFs?", answer: "Yes. You can merge up to 20 PDF files in one operation." },
      { question: "Can I change the file order?", answer: "Yes. Use the move controls on each file before merging." },
      { question: "Does merging reduce quality?", answer: "Pages are copied. They are not flattened into JPG images." },
      { question: "What are the limits?", answer: "Each PDF can be up to 25 MB, with a combined limit of 200 pages." },
      { question: "Can I merge on a phone?", answer: "Yes. Select files from your device and download the result." },
    ],
    relatedGuides: ["how-to-split-a-pdf", "how-to-package-multiple-pdfs-into-a-zip", "how-to-convert-word-to-pdf"],
  },
  {
    slug: "how-to-convert-pdf-to-jpg",
    title: "How to convert PDF pages to JPG",
    seoTitle: "How to Convert PDF to JPG | QuickPDFHD",
    description: "Render each PDF page as a JPEG image. A one-page file downloads as a JPG; longer files download as a ZIP of images.",
    tool: "/pdf-to-jpg",
    toolName: "PDF to JPG",
    intro: "A PDF is a document. A JPG is a picture of a page. Convert when a website, chat app, or slide deck wants an image instead of a PDF.",
    why: "Each page is drawn as an image on the server. Text becomes pixels, so you will not be able to copy wording from the JPG the way you can from the PDF.",
    formats: "Input: one PDF up to 40 pages and 25 MB. Output: a .jpg for a single page, or a ZIP of .jpg files named in page order.",
    steps: [
      "Upload the PDF on PDF to JPG.",
      "Start conversion so every page is rasterized.",
      "Download the JPG or ZIP and open the images to check readability.",
    ],
    limitations: [
      "Text is not selectable in the JPG.",
      "Extremely small print may be harder to read than in the original PDF.",
      "Encrypted PDFs need to be unlocked first.",
    ],
    tips: [
      "For the reverse task, use JPG to PDF.",
      "If you only need some pages as images, split the PDF first.",
    ],
    problems: [
      "If the download is a ZIP, the PDF had more than one page.",
      "If rendering fails, the file may be damaged, encrypted, or over the page limit.",
    ],
    faqs: [
      { question: "Does every page become an image?", answer: "Yes. Each page is rendered to its own JPG file." },
      { question: "Is this the same as renaming .pdf to .jpg?", answer: "No. Pages are drawn as images. The download is a real JPEG file (or a ZIP of JPEGs)." },
      { question: "What if my PDF has one page?", answer: "You receive a single .jpg instead of a ZIP." },
      { question: "Will text stay selectable?", answer: "No. JPG is a picture of the page." },
      { question: "What is the page limit?", answer: "Up to 40 pages and 25 MB per PDF." },
    ],
    relatedGuides: ["how-to-convert-jpg-to-pdf", "how-to-split-a-pdf", "how-to-convert-scanned-pdf-to-word"],
  },
  {
    slug: "how-to-merge-or-split-pdfs",
    title: "How to merge or split PDF files",
    description: "Combine related PDFs into one document, or extract the pages you actually need.",
    tool: "/merge-pdf",
    toolName: "Merge PDF",
    intro: "Merging copies pages from several PDFs into one file. Splitting copies selected pages out of a larger PDF. Neither tool flattens pages into photos, so existing text on those pages stays as PDF content.",
    steps: ["For a packet, add two or more PDFs to Merge PDF, set the file order, and download one document.", "For an extract, open Split PDF, choose a page range such as 1-4, 9, or split into single pages or chunks.", "Open the download and confirm page order before you send it."],
    tips: ["Unlock encrypted PDFs first.", "Page numbers follow the file order, which may differ from printed numbers.", "If you only need a ZIP of unchanged PDFs, use PDF to ZIP instead of merging."],
    relatedGuides: ["how-to-merge-pdf-files", "how-to-split-a-pdf"],
  },
];

export const guideUrl = (slug) => `https://quickpdfhd.com/pdf-guides/${slug}`;

export const findGuide = (slug) => pdfGuides.find((guide) => guide.slug === slug);

export const getGuidesForTool = (toolPath) => {
  const path = String(toolPath || "").split("#")[0];
  const resolved = path === "/jpeg-to-pdf" ? "/jpg-to-pdf" : path;
  return pdfGuides.filter((guide) => guide.tool === resolved);
};

export const getRelatedGuides = (guide) =>
  (guide.relatedGuides || [])
    .map((slug) => findGuide(slug))
    .filter(Boolean);
