export const toolExplainers = {
  "word-to-pdf": {
    whatTitle: "What Word to PDF actually does",
    what: [
      "Word files are meant to be edited. PDF files are meant to be opened, printed, or uploaded without depending on Microsoft Word. This tool reads a DOC or DOCX file on the conversion server and writes a PDF from the document’s text and basic structure.",
      "That is a real conversion of the file contents. Changing a filename from .docx to .pdf in Explorer or Finder does not create a valid PDF.",
      "The converter is built for letters, reports, notes, resumes, and similar text documents. Unusual Word themes, floating text boxes, macros, and decorative headers may look simpler in the PDF than they did in Word.",
    ],
    whenTitle: "When Word to PDF is a good fit",
    whenIntro: "Use this page when you already have a finished Word file and need a document other people can open without Word.",
    when: [
      "Emailing a letter, invoice cover note, or school assignment as an attachment",
      "Uploading a resume or statement to a portal that asks for PDF",
      "Printing a report without worrying that fonts will reflow on another computer",
      "Sharing a document with someone who should read it rather than edit the original Word file",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: one .doc or .docx file, up to 15 MB.",
      "Output: one PDF. The download name follows the uploaded filename.",
      "DOCX usually keeps more heading and table structure than a very old .doc file.",
      "Password-protected Word files are not converted until they are unlocked.",
    ],
    knowTitle: "Important things to know",
    know: [
      "Check headings, lists, tables, and images after download. Complex layout is simplified.",
      "Tracked changes and comments are not a dedicated review mode. Convert a clean copy if you only want the visible text.",
      "If special characters appear as question marks, those characters were outside the text encoding used for this converter.",
    ],
    alternativesTitle: "Word to PDF compared with other approaches",
    alternativesIntro: "There are several honest ways to get a PDF from Word. They differ in how much layout they keep and whether you need Word installed.",
    alternatives: [
      { title: "This browser tool", text: "Useful when you do not have Word on the device you are using, or you want a quick PDF from a typical text document." },
      { title: "Save as PDF inside Microsoft Word", text: "The most faithful option for designed pages, custom fonts, and headers. Use it when the layout must match Word exactly." },
      { title: "Print to PDF from another editor", text: "Works for simple documents, but print drivers vary. Always open the PDF and check page breaks." },
    ],
  },
  "pdf-to-word": {
    whatTitle: "What PDF to Word does",
    what: [
      "A PDF is often a finished page. This tool builds a .docx file from that PDF so you can edit paragraphs in Word or another editor that opens DOCX.",
      "NO OCR copies text that is already stored in the PDF. That is the right path when you can highlight sentences in a PDF viewer.",
      "OCR is a separate path for scans and photographed pages. Each page is rendered as an image, then Tesseract recognizes characters. It does not rebuild the original design.",
    ],
    whenTitle: "When to use NO OCR vs OCR",
    whenIntro: "The useful choice depends on whether the PDF already contains text objects or only pictures of text.",
    when: [
      "NO OCR: PDFs exported from Word, Excel, Google Docs, or a text editor",
      "OCR: scanned letters, photographed forms, and image-only PDFs where you cannot select text",
      "Recovering wording when the original Word file is missing",
      "Moving report paragraphs into a draft you can edit",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: one PDF up to 25 MB.",
      "NO OCR: up to 40 pages. OCR: up to 15 pages.",
      "OCR languages: English, Hindi, or English + Hindi.",
      "Output: a .docx file named from the uploaded PDF.",
      "Encrypted PDFs must be unlocked first.",
    ],
    knowTitle: "Important things to know",
    know: [
      "OCR accuracy depends on scan quality. Handwriting, blur, rotation, low contrast, and dense tables often produce errors.",
      "Columns and tables frequently become sequential lines rather than a perfect Word table.",
      "Fonts, headers, and exact page design are not reconstructed.",
      "If there is no selectable text, NO OCR cannot invent it. Switch to OCR.",
    ],
    alternativesTitle: "Other ways people get text out of a PDF",
    alternativesIntro: "PDF to Word is one workflow. Copy-paste and desktop OCR each have a place.",
    alternatives: [
      { title: "This tool", text: "Helpful when you want a DOCX from a whole file, including OCR for short scanned PDFs." },
      { title: "Copy and paste from a PDF viewer", text: "Fine for a few paragraphs of selectable text. Awkward for long reports or scans." },
      { title: "Desktop Word or Acrobat OCR", text: "Often stronger for very long scans or specialized languages. You need that software installed." },
    ],
  },
  "excel-to-pdf": {
    whatTitle: "What Excel to PDF does",
    what: [
      "Spreadsheets are for calculating. A PDF is for reading or printing a snapshot of the numbers. This converter reads worksheet cells and draws them as tables on landscape PDF pages.",
      "Charts, macros, pivot caches, and Excel objects are not drawn as they appear in Excel. Formulas are not recalculated; the PDF shows values stored in the file.",
      "Very wide sheets include up to the first 12 columns so the page stays readable. Each worksheet can include up to 400 populated rows.",
    ],
    whenTitle: "When a spreadsheet PDF is useful",
    whenIntro: "Use Excel to PDF when the recipient should see the table without opening a workbook they might accidentally change.",
    when: [
      "Emailing a budget or inventory as a document",
      "Printing a class list, attendance sheet, or price list",
      "Archiving a snapshot of worksheet data",
      "Sharing figures with people who do not use Excel",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: one .xls or .xlsx file, up to 15 MB.",
      "Output: one landscape PDF.",
      "Worksheets with no readable rows are skipped.",
      "Hidden empty sheets are not included.",
    ],
    knowTitle: "Important things to know",
    know: [
      "Put important columns on the left if the sheet is wider than 12 columns.",
      "Remove unused blank rows so the PDF stays short.",
      "If you need charts as pictures, export those from Excel and use an image-to-PDF tool.",
    ],
    alternativesTitle: "Excel to PDF compared with Excel itself",
    alternativesIntro: "Excel’s own export keeps more print layout. This tool is for a readable table snapshot in the browser.",
    alternatives: [
      { title: "This browser tool", text: "Useful for straightforward tables when you are not sitting in Excel." },
      { title: "Export or print to PDF in Excel", text: "Better for print areas, headers, freeze panes, and chart sheets." },
      { title: "Copy the range into Word first", text: "A workaround for mixed narrative-and-table reports, with extra manual cleanup." },
    ],
  },
  "pdf-to-excel": {
    whatTitle: "What PDF to Excel extracts",
    what: [
      "Many PDFs hide useful numbers in a layout that is awkward to copy. This tool groups selectable text by position on each page and writes those groups into spreadsheet rows.",
      "Each PDF page becomes its own worksheet. That makes it easier to check which page a messy row came from.",
      "This is not OCR. Image-only scans and photographed invoices have no text to extract and are rejected rather than filled with blank sheets.",
    ],
    whenTitle: "When table extraction is realistic",
    whenIntro: "Start with PDFs where you can already select table cells with a mouse.",
    when: [
      "Moving a bank or utility table into a workbook you can filter",
      "Reusing figures from a digital report without retyping",
      "Comparing exported lists once they are in Excel",
      "Preparing data for a chart after a cleanup pass",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: one PDF up to 25 MB and 40 pages, with selectable text.",
      "Output: an .xlsx workbook, one sheet per PDF page.",
      "Scanned or image-only PDFs are not extracted here.",
    ],
    knowTitle: "Important things to know",
    know: [
      "Merged cells, nested headers, and multi-line cells can land in the wrong column.",
      "Always review the spreadsheet before using it in a report.",
      "If two columns collapse into one cell, split them in Excel after download.",
      "Unlock password-protected PDFs before uploading.",
    ],
    alternativesTitle: "Other ways to get tables out of a PDF",
    alternativesIntro: "Extraction quality depends on how the PDF was created, not on a single magic setting.",
    alternatives: [
      { title: "This tool", text: "Built for selectable, table-like text. Expect a cleanup pass on complex grids." },
      { title: "Copy the table from a PDF viewer", text: "Sometimes cleaner for a small grid. Painful for long statements." },
      { title: "Export CSV from the original software", text: "The most reliable option when you still have access to the accounting or reporting system." },
    ],
  },
  "split-pdf": {
    whatTitle: "What splitting a PDF actually does",
    what: [
      "Splitting copies pages from a source PDF into a new file. Pages are not flattened into photos, so existing text and page size stay as PDF content.",
      "Extract range keeps the chosen pages in one PDF. Separate pages puts each selected page in its own PDF inside a ZIP. Chunks divide the file into several PDFs with a fixed page count each.",
      "Your original file on your device is not overwritten. You still have the full document unless you replace it yourself.",
    ],
    whenTitle: "When to extract, separate, or chunk",
    whenIntro: "Pick the mode that matches the outcome you need, not a generic “split” habit.",
    when: [
      "Extract range: a reviewer only needs a chapter or an appendix",
      "Separate pages: each certificate or form should be its own file",
      "Chunks: a long handbook needs to be broken into email-sized PDFs",
      "You want to pull pages before merging them into a different packet",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: one PDF up to 25 MB and 200 pages.",
      "Extract range returns one PDF. Separate pages and chunks return a ZIP of PDFs.",
      "Page numbers follow the PDF file order, which may differ from printed numbers.",
      "Encrypted PDFs cannot be split until the password is removed.",
    ],
    knowTitle: "Important things to know",
    know: [
      "Leave the range blank in separate-pages mode to use every page.",
      "Range examples look like 1-3, 5, 8-10.",
      "If you only need several unchanged PDFs in one download, use PDF to ZIP instead of splitting.",
    ],
    alternativesTitle: "Split PDF compared with other approaches",
    alternativesIntro: "Desktop PDF software can do the same jobs with more page-preview tools. This page is for a direct extract or split in the browser.",
    alternatives: [
      { title: "This tool", text: "Fast when you already know the page numbers you need." },
      { title: "A desktop PDF editor", text: "Helpful if you want thumbnails of every page before you extract." },
      { title: "Print selected pages to a new PDF", text: "Works in some viewers, but print settings can change quality or margins." },
    ],
  },
  "merge-pdf": {
    whatTitle: "What merging PDFs does",
    what: [
      "Merging copies pages from several PDFs into one file in the order you set. It is a packaging task: instead of attaching five files, you attach one document.",
      "Pages are copied, not photographed. Mixed page sizes stay as they were in the originals. The tool does not add a table of contents or redesign layouts.",
      "If you only need some pages from a file, split first, then merge the pieces you actually want.",
    ],
    whenTitle: "When one combined PDF is useful",
    whenIntro: "Merge when related documents should be read as a single packet.",
    when: [
      "Joining a cover letter and a portfolio into one application file",
      "Combining weekly reports into a monthly packet",
      "Putting signed forms and ID scans into one submission",
      "Assembling class materials that arrived as separate downloads",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: 2 to 20 PDF files, 25 MB each.",
      "Combined page budget: 200 pages.",
      "Output: one PDF. The download name follows the first uploaded file.",
      "Use the move controls to set file order before merging.",
    ],
    knowTitle: "Important things to know",
    know: [
      "Pages inside each file keep their original order. Only the file list order is yours to change.",
      "Unlock password-protected PDFs first.",
      "Merging does not recompress pages as images, so it is not a size-reduction tool.",
      "Bookmarks and interactive forms from the sources are not rebuilt as a new outline.",
    ],
    alternativesTitle: "Merge PDF compared with ZIP or printing",
    alternativesIntro: "Combining pages is different from putting files in an archive.",
    alternatives: [
      { title: "This merge tool", text: "Use it when the recipient should open one PDF and flip through every page." },
      { title: "PDF to ZIP", text: "Use it when each PDF should stay a separate file, just grouped for download." },
      { title: "A desktop PDF suite", text: "Useful for large packets, outlines, and page-level preview before you commit." },
    ],
  },
  "jpg-to-pdf": {
    whatTitle: "What JPG to PDF does",
    what: [
      "This converter places each uploaded JPG or JPEG photo on its own A4 PDF page, scaled to fit and centered. It does not OCR the picture, so handwriting and printed text stay as pixels.",
      "JPG and JPEG are the same image codec; cameras and phones may save .jpg or .jpeg. This page accepts both, including a mix in one upload.",
      "You can add up to 20 images, then drag the previews so the PDF reads in the order someone would flip paper pages.",
    ],
    whenTitle: "When a JPG PDF is the right document",
    whenIntro: "Build a PDF from photos when the destination wants one file instead of a gallery of attachments.",
    when: [
      "Photographing homework, receipts, or notes on a phone saved as .jpg or .jpeg",
      "Collecting event photos that should be reviewed as a short booklet",
      "Uploading image pages to a portal that only accepts PDF",
      "Emailing several pictures as one attachment",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: .jpg and .jpeg images, up to 20 files, 10 MB each.",
      "Output: one A4 PDF. Images are fitted to the page; they are not cropped to fill the sheet.",
      "Page order follows the preview list, which you can drag before conversion.",
      "For photographed paperwork that needs edge trim, color modes, or a size goal, Document Scanner is the better tool.",
    ],
    knowTitle: "Important things to know",
    know: [
      "Blurry or dark photos stay blurry in the PDF. Retake the picture first.",
      "Very tall or wide photos leave more white margin on an A4 page.",
      "This is not a scan cleaner. White-edge cropping lives on Document Scanner.",
      "PDF pages can be converted to images using dedicated PDF software if you later need a picture of a page.",
    ],
    alternativesTitle: "JPG to PDF compared with other approaches",
    alternativesIntro: "Putting photos in a PDF is one way to share them. A ZIP of images and a dedicated scanner each solve a different problem.",
    alternatives: [
      { title: "This converter", text: "Best when you already have .jpg or .jpeg files and need one A4 document in a chosen order." },
      { title: "Document Scanner", text: "Use it when pages need trimming, grayscale, black-and-white, page numbers, or a size target." },
      { title: "Print to PDF from a photo app", text: "Works for a single image. Awkward when you must keep twenty photos in a strict sequence." },
    ],
  },
  "png-to-pdf": {
    whatTitle: "What PNG to PDF does",
    what: [
      "PNG is a still-image format often used for screenshots, diagrams, and graphics with sharp edges. This tool places each PNG on an A4 PDF page, scaled to fit.",
      "Transparent pixels are drawn over white. The PDF page is not a transparent layer you can drop onto another background later.",
      "Use PNG when interface text and thin lines matter more than photographic grain. A heavily compressed JPG screenshot can already look muddy before it ever becomes a PDF.",
    ],
    whenTitle: "When PNG pages belong in a PDF",
    whenIntro: "A PDF of screenshots is useful when a reviewer should walk through a sequence without opening a folder of loose images.",
    when: [
      "Bug reports and support tickets that need several UI captures in order",
      "Design reviews of mockups or diagrams",
      "Step-by-step instructions built from screen grabs",
      "Printing a short visual checklist",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: .png files, up to 20 images, 10 MB each.",
      "Output: one A4 PDF. Transparency becomes white.",
      "Page order is the preview order you set.",
      "Very large pixel dimensions still fit on A4; small UI text may shrink.",
    ],
    knowTitle: "Important things to know",
    know: [
      "This is not a vector export. A PNG of a diagram is still a bitmap on the PDF page.",
      "If screenshots are huge, resize them first so the PDF is easier to email.",
      "Animated APNG is not treated as a multi-frame document.",
    ],
    alternativesTitle: "PNG to PDF compared with other sharing methods",
    alternativesIntro: "A PDF is convenient for a sequence. A live screenshot folder is better when people still need to zoom pixel-for-pixel.",
    alternatives: [
      { title: "This converter", text: "Good for an ordered packet of still screenshots." },
      { title: "Resize Image first", text: "Match widths when a mix of laptop and phone captures looks uneven on A4." },
      { title: "Paste into a word processor", text: "Useful if you need captions between images. Then use Word to PDF if the recipient wants a PDF." },
    ],
  },
  "webp-to-pdf": {
    whatTitle: "What WEBP to PDF does",
    what: [
      "WEBP is a still-image format many browsers use when you save a picture from a website. This converter places each still WEBP on an A4 PDF page.",
      "A PDF is often easier to print or attach than a handful of .webp files, which some older viewers and printers still do not open.",
      "Animated WEBP is not expanded into a page per frame. Upload a still image when you need a single document page.",
    ],
    whenTitle: "When saved web images should become a PDF",
    whenIntro: "Use this page after you have already saved WEBP files to your device and need them as one printable document.",
    when: [
      "Collecting reference graphics from a web project",
      "Printing images that arrived as WEBP downloads",
      "Sending several web graphics as one attachment",
      "Archiving a set of stills that a colleague cannot open as WEBP",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: .webp files, up to 20 images, 10 MB each.",
      "Output: one A4 PDF.",
      "Reorder previews before conversion.",
      "If a download is not actually WEBP, use the matching image-to-PDF page instead.",
    ],
    knowTitle: "Important things to know",
    know: [
      "Saving from a browser can already reduce quality. Prefer the original asset when small text matters.",
      "Mixed orientations look uneven; rotate files first.",
      "Resize Image can normalize dimensions before you build the PDF.",
    ],
    alternativesTitle: "WEBP to PDF compared with converting the images first",
    alternativesIntro: "You do not have to change WEBP to JPG on disk unless another tool requires it. This page accepts WEBP directly.",
    alternatives: [
      { title: "This converter", text: "Keeps the workflow short when files are already .webp." },
      { title: "Convert to PNG or JPG elsewhere first", text: "Only needed if you also want those formats for other software." },
      { title: "Share the WEBP files as-is", text: "Fine among people whose apps open WEBP. A PDF is the compatibility path." },
    ],
  },
  "document-scanner": {
    whatTitle: "What Document Scanner actually does",
    what: [
      "Document Scanner is for photographed paperwork, not for turning a born-digital PDF into a scan. You upload JPG, PNG, or WEBP photos of pages. The server can trim extra white edges, apply color, grayscale, or black-and-white processing, rotate pages, optionally stamp page numbers, and build an A4 PDF aimed at a size goal.",
      "You can also download the processed images without making a PDF. That is useful when a portal wants JPEG pages instead of a document.",
      "Blank and blurry warnings are a simple brightness and edge check in the browser. They are hints, not a guarantee that a page is legally complete or perfectly sharp.",
    ],
    whenTitle: "When to scan photos instead of using image-to-PDF",
    whenIntro: "Use the scanner when the photos are of paper and you need cleanup. Use JPG to PDF when the images are already finished pictures.",
    when: [
      "Photographing forms, certificates, notes, or ID pages on a phone",
      "Submitting school or office paperwork that must be a compact PDF",
      "Reducing colorful photos of text to grayscale or black-and-white",
      "Numbering pages so a reviewer can refer to page 3 of 12",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: up to 20 JPG, PNG, or WEBP images, 10 MB each.",
      "Output: one A4 PDF, and optionally processed JPEG images.",
      "Size goals: 100 KB, 200 KB, 500 KB, or 1 MB. The final PDF can be larger or smaller depending on page count and detail.",
      "Auto-crop looks for extra white margins. Dark desks and busy backgrounds can confuse the crop.",
    ],
    knowTitle: "Important things to know about phone-camera scans",
    know: [
      "Hold the phone parallel to the page in even light. Perspective warp is not a full desktop scanner correction.",
      "Glare, shadows, and thumbs in the frame stay in the result.",
      "Black-and-white mode can hide light pencil or stamps.",
      "This workflow does not run OCR. For editable text from a finished scan PDF, use PDF to Word with OCR.",
      "A size goal adjusts image quality. It is not a promise of an exact kilobyte count.",
    ],
    alternativesTitle: "Phone photos compared with a dedicated scanner",
    alternativesIntro: "A flatbed or sheet-fed scanner usually wins on even lighting. This page exists for the times you only have a camera.",
    alternatives: [
      { title: "This Document Scanner", text: "Practical for a handful of pages when you can control light and framing." },
      { title: "A hardware scanner", text: "Better for thick stacks, archival quality, and duplex paper." },
      { title: "Plain JPG to PDF", text: "Faster when photos are already cropped and you do not need scan modes." },
    ],
  },
  "pdf-to-zip": {
    whatTitle: "What PDF to ZIP does — and what it does not",
    what: [
      "This tool copies PDF files into a ZIP archive. It does not merge pages, compress PDF content, or change bookmarks. Each PDF inside the ZIP should open the same way it did before packaging.",
      "ZIP is a container. Recipients unzip the archive and still have separate documents. If they need one combined PDF, use Merge PDF instead.",
      "Store-style packaging may or may not shrink the total download. Already compressed PDFs often stay about the same size inside a ZIP.",
    ],
    whenTitle: "When a ZIP of PDFs is more useful than a merge",
    whenIntro: "Package files together when each document should remain its own file.",
    when: [
      "Sending invoices that accounting wants as separate PDFs",
      "Sharing a project folder of forms without combining them",
      "Downloading several related files in one click",
      "Keeping original filenames inside a single archive",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: 1 to 20 PDF files, 25 MB each.",
      "Output: one ZIP. Internal names follow the uploaded PDFs, with unsafe characters replaced.",
      "You can type an archive filename; unsafe characters are replaced.",
      "Non-PDF files are not packaged here.",
    ],
    knowTitle: "Important things to know",
    know: [
      "Removing a file from the list before you create the ZIP keeps it out of the archive.",
      "Password-protected PDFs are still password-protected inside the ZIP.",
      "A ZIP is not a backup system. Keep copies of important files on your own device.",
    ],
    alternativesTitle: "ZIP compared with merge and email folders",
    alternativesIntro: "Choose the container that matches how the other person will open the files.",
    alternatives: [
      { title: "This ZIP tool", text: "One download, many separate PDFs." },
      { title: "Merge PDF", text: "One document someone can scroll from cover to last page." },
      { title: "A shared drive folder", text: "Better for large sets that change over time." },
    ],
  },
  "resize-image": {
    whatTitle: "What resizing an image actually changes",
    what: [
      "Pixel width and height are the number of dots across and down. Changing those values rebuilds the picture at a new size. That is the main job of this tool.",
      "Percentage mode scales every image by the same factor from its own pixel size, using presets from 25% to 200%. The on-screen preview follows the first selected image.",
      "DPI is written as metadata. It does not add or remove pixels by itself. Print software may use DPI to guess how large the image should appear on paper.",
    ],
    whenTitle: "When to resize before sharing or converting",
    whenIntro: "Resize when a destination has a pixel limit, or when a batch of photos is larger than you need for a PDF or upload.",
    when: [
      "Preparing photos for a website that rejects huge files",
      "Making a set of screenshots similar in width",
      "Reducing pixel size before JPG to PDF so the document is lighter",
      "Setting DPI metadata for a print workflow without changing pixels",
    ],
    limitsTitle: "Supported files and limits",
    limits: [
      "Input: up to 20 JPG, PNG, or WEBP files, 10 MB each, up to 8000 pixels on a side.",
      "Output: JPG, PNG, or WEBP. Quality applies to JPG and WEBP; PNG is lossless so quality is disabled.",
      "Custom DPI metadata can be set between 36 and 1200. Leaving DPI on keep does not change pixel size.",
      "One image downloads as a single file. Several images save as separate files (folder picker when the browser supports it), not as a ZIP.",
      "Aspect-ratio lock keeps proportions. Unlocking it can stretch the picture.",
    ],
    knowTitle: "Important things to know",
    know: [
      "Enlarging a small image cannot invent missing detail. It only stretches existing pixels.",
      "Presets such as 1920 × 1080 may not match a portrait photo’s ratio. With the lock on, one side is calculated.",
      "Cropping is not offered. Unlocking aspect ratio stretches; it does not trim.",
      "This is not a PDF compressor. To shrink a photo PDF, resize the images first or use Document Scanner size goals for scans.",
    ],
    alternativesTitle: "Browser resize compared with other editors",
    alternativesIntro: "A dedicated photo editor offers crop, heal, and color tools. This page is for batch dimension and format changes.",
    alternatives: [
      { title: "This resizer", text: "Built for up to 20 files with pixels, percentage, format, quality, and DPI metadata." },
      { title: "The OS Photos app", text: "Fine for one picture. Slow when you have a folder of screenshots." },
      { title: "A print shop’s own export", text: "Use their template if they require a specific pixel box and crop." },
    ],
  },
};
